// Code generated by ent, DO NOT EDIT.

package usagelog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the usagelog type in the database.
	Label = "usage_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldCachedInputTokens holds the string denoting the cached_input_tokens field in the database.
	FieldCachedInputTokens = "cached_input_tokens"
	// FieldCacheTokens holds the string denoting the cache_tokens field in the database.
	FieldCacheTokens = "cache_tokens"
	// FieldReasoningOutputTokens holds the string denoting the reasoning_output_tokens field in the database.
	FieldReasoningOutputTokens = "reasoning_output_tokens"
	// FieldInputCost holds the string denoting the input_cost field in the database.
	FieldInputCost = "input_cost"
	// FieldOutputCost holds the string denoting the output_cost field in the database.
	FieldOutputCost = "output_cost"
	// FieldCachedInputCost holds the string denoting the cached_input_cost field in the database.
	FieldCachedInputCost = "cached_input_cost"
	// FieldCacheCost holds the string denoting the cache_cost field in the database.
	FieldCacheCost = "cache_cost"
	// FieldTotalCost holds the string denoting the total_cost field in the database.
	FieldTotalCost = "total_cost"
	// FieldActualCost holds the string denoting the actual_cost field in the database.
	FieldActualCost = "actual_cost"
	// FieldRateMultiplier holds the string denoting the rate_multiplier field in the database.
	FieldRateMultiplier = "rate_multiplier"
	// FieldAccountRateMultiplier holds the string denoting the account_rate_multiplier field in the database.
	FieldAccountRateMultiplier = "account_rate_multiplier"
	// FieldServiceTier holds the string denoting the service_tier field in the database.
	FieldServiceTier = "service_tier"
	// FieldStream holds the string denoting the stream field in the database.
	FieldStream = "stream"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldFirstTokenMs holds the string denoting the first_token_ms field in the database.
	FieldFirstTokenMs = "first_token_ms"
	// FieldUserAgent holds the string denoting the user_agent field in the database.
	FieldUserAgent = "user_agent"
	// FieldIPAddress holds the string denoting the ip_address field in the database.
	FieldIPAddress = "ip_address"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeAPIKey holds the string denoting the api_key edge name in mutations.
	EdgeAPIKey = "api_key"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// Table holds the table name of the usagelog in the database.
	Table = "usage_logs"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "usage_logs"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_usage_logs"
	// APIKeyTable is the table that holds the api_key relation/edge.
	APIKeyTable = "usage_logs"
	// APIKeyInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeyInverseTable = "api_keys"
	// APIKeyColumn is the table column denoting the api_key relation/edge.
	APIKeyColumn = "api_key_usage_logs"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "usage_logs"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_usage_logs"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "usage_logs"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_usage_logs"
)

// Columns holds all SQL columns for usagelog fields.
var Columns = []string{
	FieldID,
	FieldPlatform,
	FieldModel,
	FieldInputTokens,
	FieldOutputTokens,
	FieldCachedInputTokens,
	FieldCacheTokens,
	FieldReasoningOutputTokens,
	FieldInputCost,
	FieldOutputCost,
	FieldCachedInputCost,
	FieldCacheCost,
	FieldTotalCost,
	FieldActualCost,
	FieldRateMultiplier,
	FieldAccountRateMultiplier,
	FieldServiceTier,
	FieldStream,
	FieldDurationMs,
	FieldFirstTokenMs,
	FieldUserAgent,
	FieldIPAddress,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "usage_logs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"api_key_usage_logs",
	"account_usage_logs",
	"group_usage_logs",
	"user_usage_logs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int
	// DefaultOutputTokens holds the default value on creation for the "output_tokens" field.
	DefaultOutputTokens int
	// DefaultCachedInputTokens holds the default value on creation for the "cached_input_tokens" field.
	DefaultCachedInputTokens int
	// DefaultCacheTokens holds the default value on creation for the "cache_tokens" field.
	DefaultCacheTokens int
	// DefaultReasoningOutputTokens holds the default value on creation for the "reasoning_output_tokens" field.
	DefaultReasoningOutputTokens int
	// DefaultInputCost holds the default value on creation for the "input_cost" field.
	DefaultInputCost float64
	// DefaultOutputCost holds the default value on creation for the "output_cost" field.
	DefaultOutputCost float64
	// DefaultCachedInputCost holds the default value on creation for the "cached_input_cost" field.
	DefaultCachedInputCost float64
	// DefaultCacheCost holds the default value on creation for the "cache_cost" field.
	DefaultCacheCost float64
	// DefaultTotalCost holds the default value on creation for the "total_cost" field.
	DefaultTotalCost float64
	// DefaultActualCost holds the default value on creation for the "actual_cost" field.
	DefaultActualCost float64
	// DefaultRateMultiplier holds the default value on creation for the "rate_multiplier" field.
	DefaultRateMultiplier float64
	// DefaultAccountRateMultiplier holds the default value on creation for the "account_rate_multiplier" field.
	DefaultAccountRateMultiplier float64
	// DefaultServiceTier holds the default value on creation for the "service_tier" field.
	DefaultServiceTier string
	// DefaultStream holds the default value on creation for the "stream" field.
	DefaultStream bool
	// DefaultDurationMs holds the default value on creation for the "duration_ms" field.
	DefaultDurationMs int64
	// DefaultFirstTokenMs holds the default value on creation for the "first_token_ms" field.
	DefaultFirstTokenMs int64
	// DefaultUserAgent holds the default value on creation for the "user_agent" field.
	DefaultUserAgent string
	// DefaultIPAddress holds the default value on creation for the "ip_address" field.
	DefaultIPAddress string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the UsageLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByCachedInputTokens orders the results by the cached_input_tokens field.
func ByCachedInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachedInputTokens, opts...).ToFunc()
}

// ByCacheTokens orders the results by the cache_tokens field.
func ByCacheTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheTokens, opts...).ToFunc()
}

// ByReasoningOutputTokens orders the results by the reasoning_output_tokens field.
func ByReasoningOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReasoningOutputTokens, opts...).ToFunc()
}

// ByInputCost orders the results by the input_cost field.
func ByInputCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputCost, opts...).ToFunc()
}

// ByOutputCost orders the results by the output_cost field.
func ByOutputCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputCost, opts...).ToFunc()
}

// ByCachedInputCost orders the results by the cached_input_cost field.
func ByCachedInputCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachedInputCost, opts...).ToFunc()
}

// ByCacheCost orders the results by the cache_cost field.
func ByCacheCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCost, opts...).ToFunc()
}

// ByTotalCost orders the results by the total_cost field.
func ByTotalCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCost, opts...).ToFunc()
}

// ByActualCost orders the results by the actual_cost field.
func ByActualCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualCost, opts...).ToFunc()
}

// ByRateMultiplier orders the results by the rate_multiplier field.
func ByRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateMultiplier, opts...).ToFunc()
}

// ByAccountRateMultiplier orders the results by the account_rate_multiplier field.
func ByAccountRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountRateMultiplier, opts...).ToFunc()
}

// ByServiceTier orders the results by the service_tier field.
func ByServiceTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceTier, opts...).ToFunc()
}

// ByStream orders the results by the stream field.
func ByStream(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStream, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByFirstTokenMs orders the results by the first_token_ms field.
func ByFirstTokenMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstTokenMs, opts...).ToFunc()
}

// ByUserAgent orders the results by the user_agent field.
func ByUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAgent, opts...).ToFunc()
}

// ByIPAddress orders the results by the ip_address field.
func ByIPAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIPAddress, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByAPIKeyField orders the results by api_key field.
func ByAPIKeyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeyStep(), sql.OrderByField(field, opts...))
	}
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newAPIKeyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
	)
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
