// Code generated by ent, DO NOT EDIT.

package usagelog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldID, id))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldPlatform, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldModel, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputTokens, v))
}

// CachedInputTokens applies equality check predicate on the "cached_input_tokens" field. It's identical to CachedInputTokensEQ.
func CachedInputTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCachedInputTokens, v))
}

// CacheTokens applies equality check predicate on the "cache_tokens" field. It's identical to CacheTokensEQ.
func CacheTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheTokens, v))
}

// ReasoningOutputTokens applies equality check predicate on the "reasoning_output_tokens" field. It's identical to ReasoningOutputTokensEQ.
func ReasoningOutputTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldReasoningOutputTokens, v))
}

// InputCost applies equality check predicate on the "input_cost" field. It's identical to InputCostEQ.
func InputCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputCost, v))
}

// OutputCost applies equality check predicate on the "output_cost" field. It's identical to OutputCostEQ.
func OutputCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputCost, v))
}

// CachedInputCost applies equality check predicate on the "cached_input_cost" field. It's identical to CachedInputCostEQ.
func CachedInputCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCachedInputCost, v))
}

// CacheCost applies equality check predicate on the "cache_cost" field. It's identical to CacheCostEQ.
func CacheCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCost, v))
}

// TotalCost applies equality check predicate on the "total_cost" field. It's identical to TotalCostEQ.
func TotalCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldTotalCost, v))
}

// ActualCost applies equality check predicate on the "actual_cost" field. It's identical to ActualCostEQ.
func ActualCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldActualCost, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldRateMultiplier, v))
}

// AccountRateMultiplier applies equality check predicate on the "account_rate_multiplier" field. It's identical to AccountRateMultiplierEQ.
func AccountRateMultiplier(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldAccountRateMultiplier, v))
}

// ServiceTier applies equality check predicate on the "service_tier" field. It's identical to ServiceTierEQ.
func ServiceTier(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldServiceTier, v))
}

// Stream applies equality check predicate on the "stream" field. It's identical to StreamEQ.
func Stream(v bool) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldStream, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldDurationMs, v))
}

// FirstTokenMs applies equality check predicate on the "first_token_ms" field. It's identical to FirstTokenMsEQ.
func FirstTokenMs(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldFirstTokenMs, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUserAgent, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldIPAddress, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCreatedAt, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldPlatform, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldModel, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldInputTokens, v))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldOutputTokens, v))
}

// CachedInputTokensEQ applies the EQ predicate on the "cached_input_tokens" field.
func CachedInputTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCachedInputTokens, v))
}

// CachedInputTokensNEQ applies the NEQ predicate on the "cached_input_tokens" field.
func CachedInputTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCachedInputTokens, v))
}

// CachedInputTokensIn applies the In predicate on the "cached_input_tokens" field.
func CachedInputTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCachedInputTokens, vs...))
}

// CachedInputTokensNotIn applies the NotIn predicate on the "cached_input_tokens" field.
func CachedInputTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCachedInputTokens, vs...))
}

// CachedInputTokensGT applies the GT predicate on the "cached_input_tokens" field.
func CachedInputTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCachedInputTokens, v))
}

// CachedInputTokensGTE applies the GTE predicate on the "cached_input_tokens" field.
func CachedInputTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCachedInputTokens, v))
}

// CachedInputTokensLT applies the LT predicate on the "cached_input_tokens" field.
func CachedInputTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCachedInputTokens, v))
}

// CachedInputTokensLTE applies the LTE predicate on the "cached_input_tokens" field.
func CachedInputTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCachedInputTokens, v))
}

// CacheTokensEQ applies the EQ predicate on the "cache_tokens" field.
func CacheTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheTokens, v))
}

// CacheTokensNEQ applies the NEQ predicate on the "cache_tokens" field.
func CacheTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCacheTokens, v))
}

// CacheTokensIn applies the In predicate on the "cache_tokens" field.
func CacheTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCacheTokens, vs...))
}

// CacheTokensNotIn applies the NotIn predicate on the "cache_tokens" field.
func CacheTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCacheTokens, vs...))
}

// CacheTokensGT applies the GT predicate on the "cache_tokens" field.
func CacheTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCacheTokens, v))
}

// CacheTokensGTE applies the GTE predicate on the "cache_tokens" field.
func CacheTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCacheTokens, v))
}

// CacheTokensLT applies the LT predicate on the "cache_tokens" field.
func CacheTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCacheTokens, v))
}

// CacheTokensLTE applies the LTE predicate on the "cache_tokens" field.
func CacheTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCacheTokens, v))
}

// ReasoningOutputTokensEQ applies the EQ predicate on the "reasoning_output_tokens" field.
func ReasoningOutputTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldReasoningOutputTokens, v))
}

// ReasoningOutputTokensNEQ applies the NEQ predicate on the "reasoning_output_tokens" field.
func ReasoningOutputTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldReasoningOutputTokens, v))
}

// ReasoningOutputTokensIn applies the In predicate on the "reasoning_output_tokens" field.
func ReasoningOutputTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldReasoningOutputTokens, vs...))
}

// ReasoningOutputTokensNotIn applies the NotIn predicate on the "reasoning_output_tokens" field.
func ReasoningOutputTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldReasoningOutputTokens, vs...))
}

// ReasoningOutputTokensGT applies the GT predicate on the "reasoning_output_tokens" field.
func ReasoningOutputTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldReasoningOutputTokens, v))
}

// ReasoningOutputTokensGTE applies the GTE predicate on the "reasoning_output_tokens" field.
func ReasoningOutputTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldReasoningOutputTokens, v))
}

// ReasoningOutputTokensLT applies the LT predicate on the "reasoning_output_tokens" field.
func ReasoningOutputTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldReasoningOutputTokens, v))
}

// ReasoningOutputTokensLTE applies the LTE predicate on the "reasoning_output_tokens" field.
func ReasoningOutputTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldReasoningOutputTokens, v))
}

// InputCostEQ applies the EQ predicate on the "input_cost" field.
func InputCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputCost, v))
}

// InputCostNEQ applies the NEQ predicate on the "input_cost" field.
func InputCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldInputCost, v))
}

// InputCostIn applies the In predicate on the "input_cost" field.
func InputCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldInputCost, vs...))
}

// InputCostNotIn applies the NotIn predicate on the "input_cost" field.
func InputCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldInputCost, vs...))
}

// InputCostGT applies the GT predicate on the "input_cost" field.
func InputCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldInputCost, v))
}

// InputCostGTE applies the GTE predicate on the "input_cost" field.
func InputCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldInputCost, v))
}

// InputCostLT applies the LT predicate on the "input_cost" field.
func InputCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldInputCost, v))
}

// InputCostLTE applies the LTE predicate on the "input_cost" field.
func InputCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldInputCost, v))
}

// OutputCostEQ applies the EQ predicate on the "output_cost" field.
func OutputCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputCost, v))
}

// OutputCostNEQ applies the NEQ predicate on the "output_cost" field.
func OutputCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldOutputCost, v))
}

// OutputCostIn applies the In predicate on the "output_cost" field.
func OutputCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldOutputCost, vs...))
}

// OutputCostNotIn applies the NotIn predicate on the "output_cost" field.
func OutputCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldOutputCost, vs...))
}

// OutputCostGT applies the GT predicate on the "output_cost" field.
func OutputCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldOutputCost, v))
}

// OutputCostGTE applies the GTE predicate on the "output_cost" field.
func OutputCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldOutputCost, v))
}

// OutputCostLT applies the LT predicate on the "output_cost" field.
func OutputCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldOutputCost, v))
}

// OutputCostLTE applies the LTE predicate on the "output_cost" field.
func OutputCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldOutputCost, v))
}

// CachedInputCostEQ applies the EQ predicate on the "cached_input_cost" field.
func CachedInputCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCachedInputCost, v))
}

// CachedInputCostNEQ applies the NEQ predicate on the "cached_input_cost" field.
func CachedInputCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCachedInputCost, v))
}

// CachedInputCostIn applies the In predicate on the "cached_input_cost" field.
func CachedInputCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCachedInputCost, vs...))
}

// CachedInputCostNotIn applies the NotIn predicate on the "cached_input_cost" field.
func CachedInputCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCachedInputCost, vs...))
}

// CachedInputCostGT applies the GT predicate on the "cached_input_cost" field.
func CachedInputCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCachedInputCost, v))
}

// CachedInputCostGTE applies the GTE predicate on the "cached_input_cost" field.
func CachedInputCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCachedInputCost, v))
}

// CachedInputCostLT applies the LT predicate on the "cached_input_cost" field.
func CachedInputCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCachedInputCost, v))
}

// CachedInputCostLTE applies the LTE predicate on the "cached_input_cost" field.
func CachedInputCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCachedInputCost, v))
}

// CacheCostEQ applies the EQ predicate on the "cache_cost" field.
func CacheCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCost, v))
}

// CacheCostNEQ applies the NEQ predicate on the "cache_cost" field.
func CacheCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCacheCost, v))
}

// CacheCostIn applies the In predicate on the "cache_cost" field.
func CacheCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCacheCost, vs...))
}

// CacheCostNotIn applies the NotIn predicate on the "cache_cost" field.
func CacheCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCacheCost, vs...))
}

// CacheCostGT applies the GT predicate on the "cache_cost" field.
func CacheCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCacheCost, v))
}

// CacheCostGTE applies the GTE predicate on the "cache_cost" field.
func CacheCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCacheCost, v))
}

// CacheCostLT applies the LT predicate on the "cache_cost" field.
func CacheCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCacheCost, v))
}

// CacheCostLTE applies the LTE predicate on the "cache_cost" field.
func CacheCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCacheCost, v))
}

// TotalCostEQ applies the EQ predicate on the "total_cost" field.
func TotalCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldTotalCost, v))
}

// TotalCostNEQ applies the NEQ predicate on the "total_cost" field.
func TotalCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldTotalCost, v))
}

// TotalCostIn applies the In predicate on the "total_cost" field.
func TotalCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldTotalCost, vs...))
}

// TotalCostNotIn applies the NotIn predicate on the "total_cost" field.
func TotalCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldTotalCost, vs...))
}

// TotalCostGT applies the GT predicate on the "total_cost" field.
func TotalCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldTotalCost, v))
}

// TotalCostGTE applies the GTE predicate on the "total_cost" field.
func TotalCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldTotalCost, v))
}

// TotalCostLT applies the LT predicate on the "total_cost" field.
func TotalCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldTotalCost, v))
}

// TotalCostLTE applies the LTE predicate on the "total_cost" field.
func TotalCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldTotalCost, v))
}

// ActualCostEQ applies the EQ predicate on the "actual_cost" field.
func ActualCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldActualCost, v))
}

// ActualCostNEQ applies the NEQ predicate on the "actual_cost" field.
func ActualCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldActualCost, v))
}

// ActualCostIn applies the In predicate on the "actual_cost" field.
func ActualCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldActualCost, vs...))
}

// ActualCostNotIn applies the NotIn predicate on the "actual_cost" field.
func ActualCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldActualCost, vs...))
}

// ActualCostGT applies the GT predicate on the "actual_cost" field.
func ActualCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldActualCost, v))
}

// ActualCostGTE applies the GTE predicate on the "actual_cost" field.
func ActualCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldActualCost, v))
}

// ActualCostLT applies the LT predicate on the "actual_cost" field.
func ActualCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldActualCost, v))
}

// ActualCostLTE applies the LTE predicate on the "actual_cost" field.
func ActualCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldActualCost, v))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldRateMultiplier, v))
}

// AccountRateMultiplierEQ applies the EQ predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldAccountRateMultiplier, v))
}

// AccountRateMultiplierNEQ applies the NEQ predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldAccountRateMultiplier, v))
}

// AccountRateMultiplierIn applies the In predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldAccountRateMultiplier, vs...))
}

// AccountRateMultiplierNotIn applies the NotIn predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldAccountRateMultiplier, vs...))
}

// AccountRateMultiplierGT applies the GT predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldAccountRateMultiplier, v))
}

// AccountRateMultiplierGTE applies the GTE predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldAccountRateMultiplier, v))
}

// AccountRateMultiplierLT applies the LT predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldAccountRateMultiplier, v))
}

// AccountRateMultiplierLTE applies the LTE predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldAccountRateMultiplier, v))
}

// ServiceTierEQ applies the EQ predicate on the "service_tier" field.
func ServiceTierEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldServiceTier, v))
}

// ServiceTierNEQ applies the NEQ predicate on the "service_tier" field.
func ServiceTierNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldServiceTier, v))
}

// ServiceTierIn applies the In predicate on the "service_tier" field.
func ServiceTierIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldServiceTier, vs...))
}

// ServiceTierNotIn applies the NotIn predicate on the "service_tier" field.
func ServiceTierNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldServiceTier, vs...))
}

// ServiceTierGT applies the GT predicate on the "service_tier" field.
func ServiceTierGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldServiceTier, v))
}

// ServiceTierGTE applies the GTE predicate on the "service_tier" field.
func ServiceTierGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldServiceTier, v))
}

// ServiceTierLT applies the LT predicate on the "service_tier" field.
func ServiceTierLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldServiceTier, v))
}

// ServiceTierLTE applies the LTE predicate on the "service_tier" field.
func ServiceTierLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldServiceTier, v))
}

// ServiceTierContains applies the Contains predicate on the "service_tier" field.
func ServiceTierContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldServiceTier, v))
}

// ServiceTierHasPrefix applies the HasPrefix predicate on the "service_tier" field.
func ServiceTierHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldServiceTier, v))
}

// ServiceTierHasSuffix applies the HasSuffix predicate on the "service_tier" field.
func ServiceTierHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldServiceTier, v))
}

// ServiceTierEqualFold applies the EqualFold predicate on the "service_tier" field.
func ServiceTierEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldServiceTier, v))
}

// ServiceTierContainsFold applies the ContainsFold predicate on the "service_tier" field.
func ServiceTierContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldServiceTier, v))
}

// StreamEQ applies the EQ predicate on the "stream" field.
func StreamEQ(v bool) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldStream, v))
}

// StreamNEQ applies the NEQ predicate on the "stream" field.
func StreamNEQ(v bool) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldStream, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldDurationMs, v))
}

// FirstTokenMsEQ applies the EQ predicate on the "first_token_ms" field.
func FirstTokenMsEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldFirstTokenMs, v))
}

// FirstTokenMsNEQ applies the NEQ predicate on the "first_token_ms" field.
func FirstTokenMsNEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldFirstTokenMs, v))
}

// FirstTokenMsIn applies the In predicate on the "first_token_ms" field.
func FirstTokenMsIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldFirstTokenMs, vs...))
}

// FirstTokenMsNotIn applies the NotIn predicate on the "first_token_ms" field.
func FirstTokenMsNotIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldFirstTokenMs, vs...))
}

// FirstTokenMsGT applies the GT predicate on the "first_token_ms" field.
func FirstTokenMsGT(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldFirstTokenMs, v))
}

// FirstTokenMsGTE applies the GTE predicate on the "first_token_ms" field.
func FirstTokenMsGTE(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldFirstTokenMs, v))
}

// FirstTokenMsLT applies the LT predicate on the "first_token_ms" field.
func FirstTokenMsLT(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldFirstTokenMs, v))
}

// FirstTokenMsLTE applies the LTE predicate on the "first_token_ms" field.
func FirstTokenMsLTE(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldFirstTokenMs, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldUserAgent, v))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldIPAddress, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageLog) predicate.UsageLog {
	return predicate.UsageLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageLog) predicate.UsageLog {
	return predicate.UsageLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageLog) predicate.UsageLog {
	return predicate.UsageLog(sql.NotPredicates(p))
}
