// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/account"
	"github.com/DouDOU-start/airgate-core/ent/group"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
	"github.com/DouDOU-start/airgate-core/ent/proxy"
	"github.com/DouDOU-start/airgate-core/ent/usagelog"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (au *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetName sets the "name" field.
func (au *AccountUpdate) SetName(s string) *AccountUpdate {
	au.mutation.SetName(s)
	return au
}

// SetNillableName sets the "name" field if the given value is not nil.
func (au *AccountUpdate) SetNillableName(s *string) *AccountUpdate {
	if s != nil {
		au.SetName(*s)
	}
	return au
}

// SetPlatform sets the "platform" field.
func (au *AccountUpdate) SetPlatform(s string) *AccountUpdate {
	au.mutation.SetPlatform(s)
	return au
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (au *AccountUpdate) SetNillablePlatform(s *string) *AccountUpdate {
	if s != nil {
		au.SetPlatform(*s)
	}
	return au
}

// SetType sets the "type" field.
func (au *AccountUpdate) SetType(s string) *AccountUpdate {
	au.mutation.SetType(s)
	return au
}

// SetNillableType sets the "type" field if the given value is not nil.
func (au *AccountUpdate) SetNillableType(s *string) *AccountUpdate {
	if s != nil {
		au.SetType(*s)
	}
	return au
}

// ClearType clears the value of the "type" field.
func (au *AccountUpdate) ClearType() *AccountUpdate {
	au.mutation.ClearType()
	return au
}

// SetCredentials sets the "credentials" field.
func (au *AccountUpdate) SetCredentials(m map[string]string) *AccountUpdate {
	au.mutation.SetCredentials(m)
	return au
}

// SetStatus sets the "status" field.
func (au *AccountUpdate) SetStatus(a account.Status) *AccountUpdate {
	au.mutation.SetStatus(a)
	return au
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (au *AccountUpdate) SetNillableStatus(a *account.Status) *AccountUpdate {
	if a != nil {
		au.SetStatus(*a)
	}
	return au
}

// SetPriority sets the "priority" field.
func (au *AccountUpdate) SetPriority(i int) *AccountUpdate {
	au.mutation.ResetPriority()
	au.mutation.SetPriority(i)
	return au
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (au *AccountUpdate) SetNillablePriority(i *int) *AccountUpdate {
	if i != nil {
		au.SetPriority(*i)
	}
	return au
}

// AddPriority adds i to the "priority" field.
func (au *AccountUpdate) AddPriority(i int) *AccountUpdate {
	au.mutation.AddPriority(i)
	return au
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (au *AccountUpdate) SetMaxConcurrency(i int) *AccountUpdate {
	au.mutation.ResetMaxConcurrency()
	au.mutation.SetMaxConcurrency(i)
	return au
}

// SetNillableMaxConcurrency sets the "max_concurrency" field if the given value is not nil.
func (au *AccountUpdate) SetNillableMaxConcurrency(i *int) *AccountUpdate {
	if i != nil {
		au.SetMaxConcurrency(*i)
	}
	return au
}

// AddMaxConcurrency adds i to the "max_concurrency" field.
func (au *AccountUpdate) AddMaxConcurrency(i int) *AccountUpdate {
	au.mutation.AddMaxConcurrency(i)
	return au
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (au *AccountUpdate) SetRateMultiplier(f float64) *AccountUpdate {
	au.mutation.ResetRateMultiplier()
	au.mutation.SetRateMultiplier(f)
	return au
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (au *AccountUpdate) SetNillableRateMultiplier(f *float64) *AccountUpdate {
	if f != nil {
		au.SetRateMultiplier(*f)
	}
	return au
}

// AddRateMultiplier adds f to the "rate_multiplier" field.
func (au *AccountUpdate) AddRateMultiplier(f float64) *AccountUpdate {
	au.mutation.AddRateMultiplier(f)
	return au
}

// SetErrorMsg sets the "error_msg" field.
func (au *AccountUpdate) SetErrorMsg(s string) *AccountUpdate {
	au.mutation.SetErrorMsg(s)
	return au
}

// SetNillableErrorMsg sets the "error_msg" field if the given value is not nil.
func (au *AccountUpdate) SetNillableErrorMsg(s *string) *AccountUpdate {
	if s != nil {
		au.SetErrorMsg(*s)
	}
	return au
}

// SetLastUsedAt sets the "last_used_at" field.
func (au *AccountUpdate) SetLastUsedAt(t time.Time) *AccountUpdate {
	au.mutation.SetLastUsedAt(t)
	return au
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (au *AccountUpdate) SetNillableLastUsedAt(t *time.Time) *AccountUpdate {
	if t != nil {
		au.SetLastUsedAt(*t)
	}
	return au
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (au *AccountUpdate) ClearLastUsedAt() *AccountUpdate {
	au.mutation.ClearLastUsedAt()
	return au
}

// SetExtra sets the "extra" field.
func (au *AccountUpdate) SetExtra(m map[string]interface{}) *AccountUpdate {
	au.mutation.SetExtra(m)
	return au
}

// ClearExtra clears the value of the "extra" field.
func (au *AccountUpdate) ClearExtra() *AccountUpdate {
	au.mutation.ClearExtra()
	return au
}

// SetUpdatedAt sets the "updated_at" field.
func (au *AccountUpdate) SetUpdatedAt(t time.Time) *AccountUpdate {
	au.mutation.SetUpdatedAt(t)
	return au
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (au *AccountUpdate) AddGroupIDs(ids ...int) *AccountUpdate {
	au.mutation.AddGroupIDs(ids...)
	return au
}

// AddGroups adds the "groups" edges to the Group entity.
func (au *AccountUpdate) AddGroups(g ...*Group) *AccountUpdate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return au.AddGroupIDs(ids...)
}

// SetProxyID sets the "proxy" edge to the Proxy entity by ID.
func (au *AccountUpdate) SetProxyID(id int) *AccountUpdate {
	au.mutation.SetProxyID(id)
	return au
}

// SetNillableProxyID sets the "proxy" edge to the Proxy entity by ID if the given value is not nil.
func (au *AccountUpdate) SetNillableProxyID(id *int) *AccountUpdate {
	if id != nil {
		au = au.SetProxyID(*id)
	}
	return au
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (au *AccountUpdate) SetProxy(p *Proxy) *AccountUpdate {
	return au.SetProxyID(p.ID)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (au *AccountUpdate) AddUsageLogIDs(ids ...int) *AccountUpdate {
	au.mutation.AddUsageLogIDs(ids...)
	return au
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (au *AccountUpdate) AddUsageLogs(u ...*UsageLog) *AccountUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return au.AddUsageLogIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (au *AccountUpdate) Mutation() *AccountMutation {
	return au.mutation
}

// ClearGroups clears all "groups" edges to the Group entity.
func (au *AccountUpdate) ClearGroups() *AccountUpdate {
	au.mutation.ClearGroups()
	return au
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (au *AccountUpdate) RemoveGroupIDs(ids ...int) *AccountUpdate {
	au.mutation.RemoveGroupIDs(ids...)
	return au
}

// RemoveGroups removes "groups" edges to Group entities.
func (au *AccountUpdate) RemoveGroups(g ...*Group) *AccountUpdate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return au.RemoveGroupIDs(ids...)
}

// ClearProxy clears the "proxy" edge to the Proxy entity.
func (au *AccountUpdate) ClearProxy() *AccountUpdate {
	au.mutation.ClearProxy()
	return au
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (au *AccountUpdate) ClearUsageLogs() *AccountUpdate {
	au.mutation.ClearUsageLogs()
	return au
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (au *AccountUpdate) RemoveUsageLogIDs(ids ...int) *AccountUpdate {
	au.mutation.RemoveUsageLogIDs(ids...)
	return au
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (au *AccountUpdate) RemoveUsageLogs(u ...*UsageLog) *AccountUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return au.RemoveUsageLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AccountUpdate) Save(ctx context.Context) (int, error) {
	au.defaults()
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AccountUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AccountUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (au *AccountUpdate) defaults() {
	if _, ok := au.mutation.UpdatedAt(); !ok {
		v := account.UpdateDefaultUpdatedAt()
		au.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AccountUpdate) check() error {
	if v, ok := au.mutation.Name(); ok {
		if err := account.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Account.name": %w`, err)}
		}
	}
	if v, ok := au.mutation.Platform(); ok {
		if err := account.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Account.platform": %w`, err)}
		}
	}
	if v, ok := au.mutation.Status(); ok {
		if err := account.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Account.status": %w`, err)}
		}
	}
	if v, ok := au.mutation.Priority(); ok {
		if err := account.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Account.priority": %w`, err)}
		}
	}
	return nil
}

func (au *AccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := au.mutation.Platform(); ok {
		_spec.SetField(account.FieldPlatform, field.TypeString, value)
	}
	if value, ok := au.mutation.GetType(); ok {
		_spec.SetField(account.FieldType, field.TypeString, value)
	}
	if au.mutation.TypeCleared() {
		_spec.ClearField(account.FieldType, field.TypeString)
	}
	if value, ok := au.mutation.Credentials(); ok {
		_spec.SetField(account.FieldCredentials, field.TypeJSON, value)
	}
	if value, ok := au.mutation.Status(); ok {
		_spec.SetField(account.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := au.mutation.Priority(); ok {
		_spec.SetField(account.FieldPriority, field.TypeInt, value)
	}
	if value, ok := au.mutation.AddedPriority(); ok {
		_spec.AddField(account.FieldPriority, field.TypeInt, value)
	}
	if value, ok := au.mutation.MaxConcurrency(); ok {
		_spec.SetField(account.FieldMaxConcurrency, field.TypeInt, value)
	}
	if value, ok := au.mutation.AddedMaxConcurrency(); ok {
		_spec.AddField(account.FieldMaxConcurrency, field.TypeInt, value)
	}
	if value, ok := au.mutation.RateMultiplier(); ok {
		_spec.SetField(account.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := au.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(account.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := au.mutation.ErrorMsg(); ok {
		_spec.SetField(account.FieldErrorMsg, field.TypeString, value)
	}
	if value, ok := au.mutation.LastUsedAt(); ok {
		_spec.SetField(account.FieldLastUsedAt, field.TypeTime, value)
	}
	if au.mutation.LastUsedAtCleared() {
		_spec.ClearField(account.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := au.mutation.Extra(); ok {
		_spec.SetField(account.FieldExtra, field.TypeJSON, value)
	}
	if au.mutation.ExtraCleared() {
		_spec.ClearField(account.FieldExtra, field.TypeJSON)
	}
	if value, ok := au.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
	}
	if au.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   account.GroupsTable,
			Columns: account.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !au.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   account.GroupsTable,
			Columns: account.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   account.GroupsTable,
			Columns: account.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.ProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.ProxyTable,
			Columns: []string{account.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.ProxyTable,
			Columns: []string{account.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.UsageLogsTable,
			Columns: []string{account.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !au.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.UsageLogsTable,
			Columns: []string{account.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.UsageLogsTable,
			Columns: []string{account.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetName sets the "name" field.
func (auo *AccountUpdateOne) SetName(s string) *AccountUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableName(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetName(*s)
	}
	return auo
}

// SetPlatform sets the "platform" field.
func (auo *AccountUpdateOne) SetPlatform(s string) *AccountUpdateOne {
	auo.mutation.SetPlatform(s)
	return auo
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillablePlatform(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetPlatform(*s)
	}
	return auo
}

// SetType sets the "type" field.
func (auo *AccountUpdateOne) SetType(s string) *AccountUpdateOne {
	auo.mutation.SetType(s)
	return auo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableType(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetType(*s)
	}
	return auo
}

// ClearType clears the value of the "type" field.
func (auo *AccountUpdateOne) ClearType() *AccountUpdateOne {
	auo.mutation.ClearType()
	return auo
}

// SetCredentials sets the "credentials" field.
func (auo *AccountUpdateOne) SetCredentials(m map[string]string) *AccountUpdateOne {
	auo.mutation.SetCredentials(m)
	return auo
}

// SetStatus sets the "status" field.
func (auo *AccountUpdateOne) SetStatus(a account.Status) *AccountUpdateOne {
	auo.mutation.SetStatus(a)
	return auo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableStatus(a *account.Status) *AccountUpdateOne {
	if a != nil {
		auo.SetStatus(*a)
	}
	return auo
}

// SetPriority sets the "priority" field.
func (auo *AccountUpdateOne) SetPriority(i int) *AccountUpdateOne {
	auo.mutation.ResetPriority()
	auo.mutation.SetPriority(i)
	return auo
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillablePriority(i *int) *AccountUpdateOne {
	if i != nil {
		auo.SetPriority(*i)
	}
	return auo
}

// AddPriority adds i to the "priority" field.
func (auo *AccountUpdateOne) AddPriority(i int) *AccountUpdateOne {
	auo.mutation.AddPriority(i)
	return auo
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (auo *AccountUpdateOne) SetMaxConcurrency(i int) *AccountUpdateOne {
	auo.mutation.ResetMaxConcurrency()
	auo.mutation.SetMaxConcurrency(i)
	return auo
}

// SetNillableMaxConcurrency sets the "max_concurrency" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableMaxConcurrency(i *int) *AccountUpdateOne {
	if i != nil {
		auo.SetMaxConcurrency(*i)
	}
	return auo
}

// AddMaxConcurrency adds i to the "max_concurrency" field.
func (auo *AccountUpdateOne) AddMaxConcurrency(i int) *AccountUpdateOne {
	auo.mutation.AddMaxConcurrency(i)
	return auo
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (auo *AccountUpdateOne) SetRateMultiplier(f float64) *AccountUpdateOne {
	auo.mutation.ResetRateMultiplier()
	auo.mutation.SetRateMultiplier(f)
	return auo
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableRateMultiplier(f *float64) *AccountUpdateOne {
	if f != nil {
		auo.SetRateMultiplier(*f)
	}
	return auo
}

// AddRateMultiplier adds f to the "rate_multiplier" field.
func (auo *AccountUpdateOne) AddRateMultiplier(f float64) *AccountUpdateOne {
	auo.mutation.AddRateMultiplier(f)
	return auo
}

// SetErrorMsg sets the "error_msg" field.
func (auo *AccountUpdateOne) SetErrorMsg(s string) *AccountUpdateOne {
	auo.mutation.SetErrorMsg(s)
	return auo
}

// SetNillableErrorMsg sets the "error_msg" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableErrorMsg(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetErrorMsg(*s)
	}
	return auo
}

// SetLastUsedAt sets the "last_used_at" field.
func (auo *AccountUpdateOne) SetLastUsedAt(t time.Time) *AccountUpdateOne {
	auo.mutation.SetLastUsedAt(t)
	return auo
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableLastUsedAt(t *time.Time) *AccountUpdateOne {
	if t != nil {
		auo.SetLastUsedAt(*t)
	}
	return auo
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (auo *AccountUpdateOne) ClearLastUsedAt() *AccountUpdateOne {
	auo.mutation.ClearLastUsedAt()
	return auo
}

// SetExtra sets the "extra" field.
func (auo *AccountUpdateOne) SetExtra(m map[string]interface{}) *AccountUpdateOne {
	auo.mutation.SetExtra(m)
	return auo
}

// ClearExtra clears the value of the "extra" field.
func (auo *AccountUpdateOne) ClearExtra() *AccountUpdateOne {
	auo.mutation.ClearExtra()
	return auo
}

// SetUpdatedAt sets the "updated_at" field.
func (auo *AccountUpdateOne) SetUpdatedAt(t time.Time) *AccountUpdateOne {
	auo.mutation.SetUpdatedAt(t)
	return auo
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (auo *AccountUpdateOne) AddGroupIDs(ids ...int) *AccountUpdateOne {
	auo.mutation.AddGroupIDs(ids...)
	return auo
}

// AddGroups adds the "groups" edges to the Group entity.
func (auo *AccountUpdateOne) AddGroups(g ...*Group) *AccountUpdateOne {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return auo.AddGroupIDs(ids...)
}

// SetProxyID sets the "proxy" edge to the Proxy entity by ID.
func (auo *AccountUpdateOne) SetProxyID(id int) *AccountUpdateOne {
	auo.mutation.SetProxyID(id)
	return auo
}

// SetNillableProxyID sets the "proxy" edge to the Proxy entity by ID if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableProxyID(id *int) *AccountUpdateOne {
	if id != nil {
		auo = auo.SetProxyID(*id)
	}
	return auo
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (auo *AccountUpdateOne) SetProxy(p *Proxy) *AccountUpdateOne {
	return auo.SetProxyID(p.ID)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (auo *AccountUpdateOne) AddUsageLogIDs(ids ...int) *AccountUpdateOne {
	auo.mutation.AddUsageLogIDs(ids...)
	return auo
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (auo *AccountUpdateOne) AddUsageLogs(u ...*UsageLog) *AccountUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return auo.AddUsageLogIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (auo *AccountUpdateOne) Mutation() *AccountMutation {
	return auo.mutation
}

// ClearGroups clears all "groups" edges to the Group entity.
func (auo *AccountUpdateOne) ClearGroups() *AccountUpdateOne {
	auo.mutation.ClearGroups()
	return auo
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (auo *AccountUpdateOne) RemoveGroupIDs(ids ...int) *AccountUpdateOne {
	auo.mutation.RemoveGroupIDs(ids...)
	return auo
}

// RemoveGroups removes "groups" edges to Group entities.
func (auo *AccountUpdateOne) RemoveGroups(g ...*Group) *AccountUpdateOne {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return auo.RemoveGroupIDs(ids...)
}

// ClearProxy clears the "proxy" edge to the Proxy entity.
func (auo *AccountUpdateOne) ClearProxy() *AccountUpdateOne {
	auo.mutation.ClearProxy()
	return auo
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (auo *AccountUpdateOne) ClearUsageLogs() *AccountUpdateOne {
	auo.mutation.ClearUsageLogs()
	return auo
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (auo *AccountUpdateOne) RemoveUsageLogIDs(ids ...int) *AccountUpdateOne {
	auo.mutation.RemoveUsageLogIDs(ids...)
	return auo
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (auo *AccountUpdateOne) RemoveUsageLogs(u ...*UsageLog) *AccountUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return auo.RemoveUsageLogIDs(ids...)
}

// Where appends a list predicates to the AccountUpdate builder.
func (auo *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Account entity.
func (auo *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	auo.defaults()
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auo *AccountUpdateOne) defaults() {
	if _, ok := auo.mutation.UpdatedAt(); !ok {
		v := account.UpdateDefaultUpdatedAt()
		auo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AccountUpdateOne) check() error {
	if v, ok := auo.mutation.Name(); ok {
		if err := account.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Account.name": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Platform(); ok {
		if err := account.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Account.platform": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Status(); ok {
		if err := account.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Account.status": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Priority(); ok {
		if err := account.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Account.priority": %w`, err)}
		}
	}
	return nil
}

func (auo *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := auo.mutation.Platform(); ok {
		_spec.SetField(account.FieldPlatform, field.TypeString, value)
	}
	if value, ok := auo.mutation.GetType(); ok {
		_spec.SetField(account.FieldType, field.TypeString, value)
	}
	if auo.mutation.TypeCleared() {
		_spec.ClearField(account.FieldType, field.TypeString)
	}
	if value, ok := auo.mutation.Credentials(); ok {
		_spec.SetField(account.FieldCredentials, field.TypeJSON, value)
	}
	if value, ok := auo.mutation.Status(); ok {
		_spec.SetField(account.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := auo.mutation.Priority(); ok {
		_spec.SetField(account.FieldPriority, field.TypeInt, value)
	}
	if value, ok := auo.mutation.AddedPriority(); ok {
		_spec.AddField(account.FieldPriority, field.TypeInt, value)
	}
	if value, ok := auo.mutation.MaxConcurrency(); ok {
		_spec.SetField(account.FieldMaxConcurrency, field.TypeInt, value)
	}
	if value, ok := auo.mutation.AddedMaxConcurrency(); ok {
		_spec.AddField(account.FieldMaxConcurrency, field.TypeInt, value)
	}
	if value, ok := auo.mutation.RateMultiplier(); ok {
		_spec.SetField(account.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := auo.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(account.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := auo.mutation.ErrorMsg(); ok {
		_spec.SetField(account.FieldErrorMsg, field.TypeString, value)
	}
	if value, ok := auo.mutation.LastUsedAt(); ok {
		_spec.SetField(account.FieldLastUsedAt, field.TypeTime, value)
	}
	if auo.mutation.LastUsedAtCleared() {
		_spec.ClearField(account.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := auo.mutation.Extra(); ok {
		_spec.SetField(account.FieldExtra, field.TypeJSON, value)
	}
	if auo.mutation.ExtraCleared() {
		_spec.ClearField(account.FieldExtra, field.TypeJSON)
	}
	if value, ok := auo.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
	}
	if auo.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   account.GroupsTable,
			Columns: account.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !auo.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   account.GroupsTable,
			Columns: account.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   account.GroupsTable,
			Columns: account.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.ProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.ProxyTable,
			Columns: []string{account.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.ProxyTable,
			Columns: []string{account.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.UsageLogsTable,
			Columns: []string{account.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !auo.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.UsageLogsTable,
			Columns: []string{account.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.UsageLogsTable,
			Columns: []string{account.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Account{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
