// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/apikey"
	"github.com/DouDOU-start/airgate-core/ent/group"
	"github.com/DouDOU-start/airgate-core/ent/usagelog"
	"github.com/DouDOU-start/airgate-core/ent/user"
)

// APIKeyCreate is the builder for creating a APIKey entity.
type APIKeyCreate struct {
	config
	mutation *APIKeyMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (akc *APIKeyCreate) SetName(s string) *APIKeyCreate {
	akc.mutation.SetName(s)
	return akc
}

// SetKeyHash sets the "key_hash" field.
func (akc *APIKeyCreate) SetKeyHash(s string) *APIKeyCreate {
	akc.mutation.SetKeyHash(s)
	return akc
}

// SetKeyEncrypted sets the "key_encrypted" field.
func (akc *APIKeyCreate) SetKeyEncrypted(s string) *APIKeyCreate {
	akc.mutation.SetKeyEncrypted(s)
	return akc
}

// SetNillableKeyEncrypted sets the "key_encrypted" field if the given value is not nil.
func (akc *APIKeyCreate) SetNillableKeyEncrypted(s *string) *APIKeyCreate {
	if s != nil {
		akc.SetKeyEncrypted(*s)
	}
	return akc
}

// SetIPWhitelist sets the "ip_whitelist" field.
func (akc *APIKeyCreate) SetIPWhitelist(s []string) *APIKeyCreate {
	akc.mutation.SetIPWhitelist(s)
	return akc
}

// SetIPBlacklist sets the "ip_blacklist" field.
func (akc *APIKeyCreate) SetIPBlacklist(s []string) *APIKeyCreate {
	akc.mutation.SetIPBlacklist(s)
	return akc
}

// SetQuotaUsd sets the "quota_usd" field.
func (akc *APIKeyCreate) SetQuotaUsd(f float64) *APIKeyCreate {
	akc.mutation.SetQuotaUsd(f)
	return akc
}

// SetNillableQuotaUsd sets the "quota_usd" field if the given value is not nil.
func (akc *APIKeyCreate) SetNillableQuotaUsd(f *float64) *APIKeyCreate {
	if f != nil {
		akc.SetQuotaUsd(*f)
	}
	return akc
}

// SetUsedQuota sets the "used_quota" field.
func (akc *APIKeyCreate) SetUsedQuota(f float64) *APIKeyCreate {
	akc.mutation.SetUsedQuota(f)
	return akc
}

// SetNillableUsedQuota sets the "used_quota" field if the given value is not nil.
func (akc *APIKeyCreate) SetNillableUsedQuota(f *float64) *APIKeyCreate {
	if f != nil {
		akc.SetUsedQuota(*f)
	}
	return akc
}

// SetExpiresAt sets the "expires_at" field.
func (akc *APIKeyCreate) SetExpiresAt(t time.Time) *APIKeyCreate {
	akc.mutation.SetExpiresAt(t)
	return akc
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (akc *APIKeyCreate) SetNillableExpiresAt(t *time.Time) *APIKeyCreate {
	if t != nil {
		akc.SetExpiresAt(*t)
	}
	return akc
}

// SetStatus sets the "status" field.
func (akc *APIKeyCreate) SetStatus(a apikey.Status) *APIKeyCreate {
	akc.mutation.SetStatus(a)
	return akc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (akc *APIKeyCreate) SetNillableStatus(a *apikey.Status) *APIKeyCreate {
	if a != nil {
		akc.SetStatus(*a)
	}
	return akc
}

// SetCreatedAt sets the "created_at" field.
func (akc *APIKeyCreate) SetCreatedAt(t time.Time) *APIKeyCreate {
	akc.mutation.SetCreatedAt(t)
	return akc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (akc *APIKeyCreate) SetNillableCreatedAt(t *time.Time) *APIKeyCreate {
	if t != nil {
		akc.SetCreatedAt(*t)
	}
	return akc
}

// SetUpdatedAt sets the "updated_at" field.
func (akc *APIKeyCreate) SetUpdatedAt(t time.Time) *APIKeyCreate {
	akc.mutation.SetUpdatedAt(t)
	return akc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (akc *APIKeyCreate) SetNillableUpdatedAt(t *time.Time) *APIKeyCreate {
	if t != nil {
		akc.SetUpdatedAt(*t)
	}
	return akc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (akc *APIKeyCreate) SetUserID(id int) *APIKeyCreate {
	akc.mutation.SetUserID(id)
	return akc
}

// SetUser sets the "user" edge to the User entity.
func (akc *APIKeyCreate) SetUser(u *User) *APIKeyCreate {
	return akc.SetUserID(u.ID)
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (akc *APIKeyCreate) SetGroupID(id int) *APIKeyCreate {
	akc.mutation.SetGroupID(id)
	return akc
}

// SetNillableGroupID sets the "group" edge to the Group entity by ID if the given value is not nil.
func (akc *APIKeyCreate) SetNillableGroupID(id *int) *APIKeyCreate {
	if id != nil {
		akc = akc.SetGroupID(*id)
	}
	return akc
}

// SetGroup sets the "group" edge to the Group entity.
func (akc *APIKeyCreate) SetGroup(g *Group) *APIKeyCreate {
	return akc.SetGroupID(g.ID)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (akc *APIKeyCreate) AddUsageLogIDs(ids ...int) *APIKeyCreate {
	akc.mutation.AddUsageLogIDs(ids...)
	return akc
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (akc *APIKeyCreate) AddUsageLogs(u ...*UsageLog) *APIKeyCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return akc.AddUsageLogIDs(ids...)
}

// Mutation returns the APIKeyMutation object of the builder.
func (akc *APIKeyCreate) Mutation() *APIKeyMutation {
	return akc.mutation
}

// Save creates the APIKey in the database.
func (akc *APIKeyCreate) Save(ctx context.Context) (*APIKey, error) {
	akc.defaults()
	return withHooks(ctx, akc.sqlSave, akc.mutation, akc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (akc *APIKeyCreate) SaveX(ctx context.Context) *APIKey {
	v, err := akc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (akc *APIKeyCreate) Exec(ctx context.Context) error {
	_, err := akc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (akc *APIKeyCreate) ExecX(ctx context.Context) {
	if err := akc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (akc *APIKeyCreate) defaults() {
	if _, ok := akc.mutation.QuotaUsd(); !ok {
		v := apikey.DefaultQuotaUsd
		akc.mutation.SetQuotaUsd(v)
	}
	if _, ok := akc.mutation.UsedQuota(); !ok {
		v := apikey.DefaultUsedQuota
		akc.mutation.SetUsedQuota(v)
	}
	if _, ok := akc.mutation.Status(); !ok {
		v := apikey.DefaultStatus
		akc.mutation.SetStatus(v)
	}
	if _, ok := akc.mutation.CreatedAt(); !ok {
		v := apikey.DefaultCreatedAt()
		akc.mutation.SetCreatedAt(v)
	}
	if _, ok := akc.mutation.UpdatedAt(); !ok {
		v := apikey.DefaultUpdatedAt()
		akc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (akc *APIKeyCreate) check() error {
	if _, ok := akc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "APIKey.name"`)}
	}
	if v, ok := akc.mutation.Name(); ok {
		if err := apikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "APIKey.name": %w`, err)}
		}
	}
	if _, ok := akc.mutation.KeyHash(); !ok {
		return &ValidationError{Name: "key_hash", err: errors.New(`ent: missing required field "APIKey.key_hash"`)}
	}
	if v, ok := akc.mutation.KeyHash(); ok {
		if err := apikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "APIKey.key_hash": %w`, err)}
		}
	}
	if _, ok := akc.mutation.QuotaUsd(); !ok {
		return &ValidationError{Name: "quota_usd", err: errors.New(`ent: missing required field "APIKey.quota_usd"`)}
	}
	if _, ok := akc.mutation.UsedQuota(); !ok {
		return &ValidationError{Name: "used_quota", err: errors.New(`ent: missing required field "APIKey.used_quota"`)}
	}
	if _, ok := akc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "APIKey.status"`)}
	}
	if v, ok := akc.mutation.Status(); ok {
		if err := apikey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "APIKey.status": %w`, err)}
		}
	}
	if _, ok := akc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "APIKey.created_at"`)}
	}
	if _, ok := akc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "APIKey.updated_at"`)}
	}
	if _, ok := akc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "APIKey.user"`)}
	}
	return nil
}

func (akc *APIKeyCreate) sqlSave(ctx context.Context) (*APIKey, error) {
	if err := akc.check(); err != nil {
		return nil, err
	}
	_node, _spec := akc.createSpec()
	if err := sqlgraph.CreateNode(ctx, akc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	akc.mutation.id = &_node.ID
	akc.mutation.done = true
	return _node, nil
}

func (akc *APIKeyCreate) createSpec() (*APIKey, *sqlgraph.CreateSpec) {
	var (
		_node = &APIKey{config: akc.config}
		_spec = sqlgraph.NewCreateSpec(apikey.Table, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt))
	)
	if value, ok := akc.mutation.Name(); ok {
		_spec.SetField(apikey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := akc.mutation.KeyHash(); ok {
		_spec.SetField(apikey.FieldKeyHash, field.TypeString, value)
		_node.KeyHash = value
	}
	if value, ok := akc.mutation.KeyEncrypted(); ok {
		_spec.SetField(apikey.FieldKeyEncrypted, field.TypeString, value)
		_node.KeyEncrypted = value
	}
	if value, ok := akc.mutation.IPWhitelist(); ok {
		_spec.SetField(apikey.FieldIPWhitelist, field.TypeJSON, value)
		_node.IPWhitelist = value
	}
	if value, ok := akc.mutation.IPBlacklist(); ok {
		_spec.SetField(apikey.FieldIPBlacklist, field.TypeJSON, value)
		_node.IPBlacklist = value
	}
	if value, ok := akc.mutation.QuotaUsd(); ok {
		_spec.SetField(apikey.FieldQuotaUsd, field.TypeFloat64, value)
		_node.QuotaUsd = value
	}
	if value, ok := akc.mutation.UsedQuota(); ok {
		_spec.SetField(apikey.FieldUsedQuota, field.TypeFloat64, value)
		_node.UsedQuota = value
	}
	if value, ok := akc.mutation.ExpiresAt(); ok {
		_spec.SetField(apikey.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := akc.mutation.Status(); ok {
		_spec.SetField(apikey.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := akc.mutation.CreatedAt(); ok {
		_spec.SetField(apikey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := akc.mutation.UpdatedAt(); ok {
		_spec.SetField(apikey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := akc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.UserTable,
			Columns: []string{apikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_api_keys = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := akc.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.GroupTable,
			Columns: []string{apikey.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.group_api_keys = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := akc.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apikey.UsageLogsTable,
			Columns: []string{apikey.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// APIKeyCreateBulk is the builder for creating many APIKey entities in bulk.
type APIKeyCreateBulk struct {
	config
	err      error
	builders []*APIKeyCreate
}

// Save creates the APIKey entities in the database.
func (akcb *APIKeyCreateBulk) Save(ctx context.Context) ([]*APIKey, error) {
	if akcb.err != nil {
		return nil, akcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(akcb.builders))
	nodes := make([]*APIKey, len(akcb.builders))
	mutators := make([]Mutator, len(akcb.builders))
	for i := range akcb.builders {
		func(i int, root context.Context) {
			builder := akcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APIKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, akcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, akcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, akcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (akcb *APIKeyCreateBulk) SaveX(ctx context.Context) []*APIKey {
	v, err := akcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (akcb *APIKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := akcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (akcb *APIKeyCreateBulk) ExecX(ctx context.Context) {
	if err := akcb.Exec(ctx); err != nil {
		panic(err)
	}
}
