// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/account"
	"github.com/DouDOU-start/airgate-core/ent/apikey"
	"github.com/DouDOU-start/airgate-core/ent/group"
	"github.com/DouDOU-start/airgate-core/ent/usagelog"
	"github.com/DouDOU-start/airgate-core/ent/user"
	"github.com/DouDOU-start/airgate-core/ent/usersubscription"
)

// GroupCreate is the builder for creating a Group entity.
type GroupCreate struct {
	config
	mutation *GroupMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (gc *GroupCreate) SetName(s string) *GroupCreate {
	gc.mutation.SetName(s)
	return gc
}

// SetPlatform sets the "platform" field.
func (gc *GroupCreate) SetPlatform(s string) *GroupCreate {
	gc.mutation.SetPlatform(s)
	return gc
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (gc *GroupCreate) SetRateMultiplier(f float64) *GroupCreate {
	gc.mutation.SetRateMultiplier(f)
	return gc
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (gc *GroupCreate) SetNillableRateMultiplier(f *float64) *GroupCreate {
	if f != nil {
		gc.SetRateMultiplier(*f)
	}
	return gc
}

// SetIsExclusive sets the "is_exclusive" field.
func (gc *GroupCreate) SetIsExclusive(b bool) *GroupCreate {
	gc.mutation.SetIsExclusive(b)
	return gc
}

// SetNillableIsExclusive sets the "is_exclusive" field if the given value is not nil.
func (gc *GroupCreate) SetNillableIsExclusive(b *bool) *GroupCreate {
	if b != nil {
		gc.SetIsExclusive(*b)
	}
	return gc
}

// SetSubscriptionType sets the "subscription_type" field.
func (gc *GroupCreate) SetSubscriptionType(gt group.SubscriptionType) *GroupCreate {
	gc.mutation.SetSubscriptionType(gt)
	return gc
}

// SetNillableSubscriptionType sets the "subscription_type" field if the given value is not nil.
func (gc *GroupCreate) SetNillableSubscriptionType(gt *group.SubscriptionType) *GroupCreate {
	if gt != nil {
		gc.SetSubscriptionType(*gt)
	}
	return gc
}

// SetQuotas sets the "quotas" field.
func (gc *GroupCreate) SetQuotas(m map[string]interface{}) *GroupCreate {
	gc.mutation.SetQuotas(m)
	return gc
}

// SetModelRouting sets the "model_routing" field.
func (gc *GroupCreate) SetModelRouting(m map[string][]int64) *GroupCreate {
	gc.mutation.SetModelRouting(m)
	return gc
}

// SetServiceTier sets the "service_tier" field.
func (gc *GroupCreate) SetServiceTier(s string) *GroupCreate {
	gc.mutation.SetServiceTier(s)
	return gc
}

// SetNillableServiceTier sets the "service_tier" field if the given value is not nil.
func (gc *GroupCreate) SetNillableServiceTier(s *string) *GroupCreate {
	if s != nil {
		gc.SetServiceTier(*s)
	}
	return gc
}

// SetForceInstructions sets the "force_instructions" field.
func (gc *GroupCreate) SetForceInstructions(s string) *GroupCreate {
	gc.mutation.SetForceInstructions(s)
	return gc
}

// SetNillableForceInstructions sets the "force_instructions" field if the given value is not nil.
func (gc *GroupCreate) SetNillableForceInstructions(s *string) *GroupCreate {
	if s != nil {
		gc.SetForceInstructions(*s)
	}
	return gc
}

// SetNote sets the "note" field.
func (gc *GroupCreate) SetNote(s string) *GroupCreate {
	gc.mutation.SetNote(s)
	return gc
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (gc *GroupCreate) SetNillableNote(s *string) *GroupCreate {
	if s != nil {
		gc.SetNote(*s)
	}
	return gc
}

// SetSortWeight sets the "sort_weight" field.
func (gc *GroupCreate) SetSortWeight(i int) *GroupCreate {
	gc.mutation.SetSortWeight(i)
	return gc
}

// SetNillableSortWeight sets the "sort_weight" field if the given value is not nil.
func (gc *GroupCreate) SetNillableSortWeight(i *int) *GroupCreate {
	if i != nil {
		gc.SetSortWeight(*i)
	}
	return gc
}

// SetCreatedAt sets the "created_at" field.
func (gc *GroupCreate) SetCreatedAt(t time.Time) *GroupCreate {
	gc.mutation.SetCreatedAt(t)
	return gc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (gc *GroupCreate) SetNillableCreatedAt(t *time.Time) *GroupCreate {
	if t != nil {
		gc.SetCreatedAt(*t)
	}
	return gc
}

// SetUpdatedAt sets the "updated_at" field.
func (gc *GroupCreate) SetUpdatedAt(t time.Time) *GroupCreate {
	gc.mutation.SetUpdatedAt(t)
	return gc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (gc *GroupCreate) SetNillableUpdatedAt(t *time.Time) *GroupCreate {
	if t != nil {
		gc.SetUpdatedAt(*t)
	}
	return gc
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (gc *GroupCreate) AddAccountIDs(ids ...int) *GroupCreate {
	gc.mutation.AddAccountIDs(ids...)
	return gc
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (gc *GroupCreate) AddAccounts(a ...*Account) *GroupCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return gc.AddAccountIDs(ids...)
}

// AddAllowedUserIDs adds the "allowed_users" edge to the User entity by IDs.
func (gc *GroupCreate) AddAllowedUserIDs(ids ...int) *GroupCreate {
	gc.mutation.AddAllowedUserIDs(ids...)
	return gc
}

// AddAllowedUsers adds the "allowed_users" edges to the User entity.
func (gc *GroupCreate) AddAllowedUsers(u ...*User) *GroupCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return gc.AddAllowedUserIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (gc *GroupCreate) AddAPIKeyIDs(ids ...int) *GroupCreate {
	gc.mutation.AddAPIKeyIDs(ids...)
	return gc
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (gc *GroupCreate) AddAPIKeys(a ...*APIKey) *GroupCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return gc.AddAPIKeyIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the UserSubscription entity by IDs.
func (gc *GroupCreate) AddSubscriptionIDs(ids ...int) *GroupCreate {
	gc.mutation.AddSubscriptionIDs(ids...)
	return gc
}

// AddSubscriptions adds the "subscriptions" edges to the UserSubscription entity.
func (gc *GroupCreate) AddSubscriptions(u ...*UserSubscription) *GroupCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return gc.AddSubscriptionIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (gc *GroupCreate) AddUsageLogIDs(ids ...int) *GroupCreate {
	gc.mutation.AddUsageLogIDs(ids...)
	return gc
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (gc *GroupCreate) AddUsageLogs(u ...*UsageLog) *GroupCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return gc.AddUsageLogIDs(ids...)
}

// Mutation returns the GroupMutation object of the builder.
func (gc *GroupCreate) Mutation() *GroupMutation {
	return gc.mutation
}

// Save creates the Group in the database.
func (gc *GroupCreate) Save(ctx context.Context) (*Group, error) {
	gc.defaults()
	return withHooks(ctx, gc.sqlSave, gc.mutation, gc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (gc *GroupCreate) SaveX(ctx context.Context) *Group {
	v, err := gc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gc *GroupCreate) Exec(ctx context.Context) error {
	_, err := gc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gc *GroupCreate) ExecX(ctx context.Context) {
	if err := gc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gc *GroupCreate) defaults() {
	if _, ok := gc.mutation.RateMultiplier(); !ok {
		v := group.DefaultRateMultiplier
		gc.mutation.SetRateMultiplier(v)
	}
	if _, ok := gc.mutation.IsExclusive(); !ok {
		v := group.DefaultIsExclusive
		gc.mutation.SetIsExclusive(v)
	}
	if _, ok := gc.mutation.SubscriptionType(); !ok {
		v := group.DefaultSubscriptionType
		gc.mutation.SetSubscriptionType(v)
	}
	if _, ok := gc.mutation.ServiceTier(); !ok {
		v := group.DefaultServiceTier
		gc.mutation.SetServiceTier(v)
	}
	if _, ok := gc.mutation.ForceInstructions(); !ok {
		v := group.DefaultForceInstructions
		gc.mutation.SetForceInstructions(v)
	}
	if _, ok := gc.mutation.Note(); !ok {
		v := group.DefaultNote
		gc.mutation.SetNote(v)
	}
	if _, ok := gc.mutation.SortWeight(); !ok {
		v := group.DefaultSortWeight
		gc.mutation.SetSortWeight(v)
	}
	if _, ok := gc.mutation.CreatedAt(); !ok {
		v := group.DefaultCreatedAt()
		gc.mutation.SetCreatedAt(v)
	}
	if _, ok := gc.mutation.UpdatedAt(); !ok {
		v := group.DefaultUpdatedAt()
		gc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gc *GroupCreate) check() error {
	if _, ok := gc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Group.name"`)}
	}
	if v, ok := gc.mutation.Name(); ok {
		if err := group.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Group.name": %w`, err)}
		}
	}
	if _, ok := gc.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Group.platform"`)}
	}
	if v, ok := gc.mutation.Platform(); ok {
		if err := group.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Group.platform": %w`, err)}
		}
	}
	if _, ok := gc.mutation.RateMultiplier(); !ok {
		return &ValidationError{Name: "rate_multiplier", err: errors.New(`ent: missing required field "Group.rate_multiplier"`)}
	}
	if _, ok := gc.mutation.IsExclusive(); !ok {
		return &ValidationError{Name: "is_exclusive", err: errors.New(`ent: missing required field "Group.is_exclusive"`)}
	}
	if _, ok := gc.mutation.SubscriptionType(); !ok {
		return &ValidationError{Name: "subscription_type", err: errors.New(`ent: missing required field "Group.subscription_type"`)}
	}
	if v, ok := gc.mutation.SubscriptionType(); ok {
		if err := group.SubscriptionTypeValidator(v); err != nil {
			return &ValidationError{Name: "subscription_type", err: fmt.Errorf(`ent: validator failed for field "Group.subscription_type": %w`, err)}
		}
	}
	if _, ok := gc.mutation.ServiceTier(); !ok {
		return &ValidationError{Name: "service_tier", err: errors.New(`ent: missing required field "Group.service_tier"`)}
	}
	if _, ok := gc.mutation.ForceInstructions(); !ok {
		return &ValidationError{Name: "force_instructions", err: errors.New(`ent: missing required field "Group.force_instructions"`)}
	}
	if _, ok := gc.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "Group.note"`)}
	}
	if _, ok := gc.mutation.SortWeight(); !ok {
		return &ValidationError{Name: "sort_weight", err: errors.New(`ent: missing required field "Group.sort_weight"`)}
	}
	if _, ok := gc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Group.created_at"`)}
	}
	if _, ok := gc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Group.updated_at"`)}
	}
	return nil
}

func (gc *GroupCreate) sqlSave(ctx context.Context) (*Group, error) {
	if err := gc.check(); err != nil {
		return nil, err
	}
	_node, _spec := gc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	gc.mutation.id = &_node.ID
	gc.mutation.done = true
	return _node, nil
}

func (gc *GroupCreate) createSpec() (*Group, *sqlgraph.CreateSpec) {
	var (
		_node = &Group{config: gc.config}
		_spec = sqlgraph.NewCreateSpec(group.Table, sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt))
	)
	if value, ok := gc.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := gc.mutation.Platform(); ok {
		_spec.SetField(group.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := gc.mutation.RateMultiplier(); ok {
		_spec.SetField(group.FieldRateMultiplier, field.TypeFloat64, value)
		_node.RateMultiplier = value
	}
	if value, ok := gc.mutation.IsExclusive(); ok {
		_spec.SetField(group.FieldIsExclusive, field.TypeBool, value)
		_node.IsExclusive = value
	}
	if value, ok := gc.mutation.SubscriptionType(); ok {
		_spec.SetField(group.FieldSubscriptionType, field.TypeEnum, value)
		_node.SubscriptionType = value
	}
	if value, ok := gc.mutation.Quotas(); ok {
		_spec.SetField(group.FieldQuotas, field.TypeJSON, value)
		_node.Quotas = value
	}
	if value, ok := gc.mutation.ModelRouting(); ok {
		_spec.SetField(group.FieldModelRouting, field.TypeJSON, value)
		_node.ModelRouting = value
	}
	if value, ok := gc.mutation.ServiceTier(); ok {
		_spec.SetField(group.FieldServiceTier, field.TypeString, value)
		_node.ServiceTier = value
	}
	if value, ok := gc.mutation.ForceInstructions(); ok {
		_spec.SetField(group.FieldForceInstructions, field.TypeString, value)
		_node.ForceInstructions = value
	}
	if value, ok := gc.mutation.Note(); ok {
		_spec.SetField(group.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := gc.mutation.SortWeight(); ok {
		_spec.SetField(group.FieldSortWeight, field.TypeInt, value)
		_node.SortWeight = value
	}
	if value, ok := gc.mutation.CreatedAt(); ok {
		_spec.SetField(group.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := gc.mutation.UpdatedAt(); ok {
		_spec.SetField(group.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := gc.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.AccountsTable,
			Columns: group.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := gc.mutation.AllowedUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.AllowedUsersTable,
			Columns: group.AllowedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := gc.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.APIKeysTable,
			Columns: []string{group.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := gc.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.SubscriptionsTable,
			Columns: []string{group.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := gc.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.UsageLogsTable,
			Columns: []string{group.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GroupCreateBulk is the builder for creating many Group entities in bulk.
type GroupCreateBulk struct {
	config
	err      error
	builders []*GroupCreate
}

// Save creates the Group entities in the database.
func (gcb *GroupCreateBulk) Save(ctx context.Context) ([]*Group, error) {
	if gcb.err != nil {
		return nil, gcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(gcb.builders))
	nodes := make([]*Group, len(gcb.builders))
	mutators := make([]Mutator, len(gcb.builders))
	for i := range gcb.builders {
		func(i int, root context.Context) {
			builder := gcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gcb *GroupCreateBulk) SaveX(ctx context.Context) []*Group {
	v, err := gcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gcb *GroupCreateBulk) Exec(ctx context.Context) error {
	_, err := gcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gcb *GroupCreateBulk) ExecX(ctx context.Context) {
	if err := gcb.Exec(ctx); err != nil {
		panic(err)
	}
}
