// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/DouDOU-start/airgate-core/ent/account"
	"github.com/DouDOU-start/airgate-core/ent/apikey"
	"github.com/DouDOU-start/airgate-core/ent/balancelog"
	"github.com/DouDOU-start/airgate-core/ent/group"
	"github.com/DouDOU-start/airgate-core/ent/order"
	"github.com/DouDOU-start/airgate-core/ent/plugin"
	"github.com/DouDOU-start/airgate-core/ent/pluginsource"
	"github.com/DouDOU-start/airgate-core/ent/proxy"
	"github.com/DouDOU-start/airgate-core/ent/schema"
	"github.com/DouDOU-start/airgate-core/ent/setting"
	"github.com/DouDOU-start/airgate-core/ent/usagelog"
	"github.com/DouDOU-start/airgate-core/ent/user"
	"github.com/DouDOU-start/airgate-core/ent/usersubscription"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apikeyFields := schema.APIKey{}.Fields()
	_ = apikeyFields
	// apikeyDescName is the schema descriptor for name field.
	apikeyDescName := apikeyFields[0].Descriptor()
	// apikey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	apikey.NameValidator = apikeyDescName.Validators[0].(func(string) error)
	// apikeyDescKeyHash is the schema descriptor for key_hash field.
	apikeyDescKeyHash := apikeyFields[1].Descriptor()
	// apikey.KeyHashValidator is a validator for the "key_hash" field. It is called by the builders before save.
	apikey.KeyHashValidator = apikeyDescKeyHash.Validators[0].(func(string) error)
	// apikeyDescQuotaUsd is the schema descriptor for quota_usd field.
	apikeyDescQuotaUsd := apikeyFields[5].Descriptor()
	// apikey.DefaultQuotaUsd holds the default value on creation for the quota_usd field.
	apikey.DefaultQuotaUsd = apikeyDescQuotaUsd.Default.(float64)
	// apikeyDescUsedQuota is the schema descriptor for used_quota field.
	apikeyDescUsedQuota := apikeyFields[6].Descriptor()
	// apikey.DefaultUsedQuota holds the default value on creation for the used_quota field.
	apikey.DefaultUsedQuota = apikeyDescUsedQuota.Default.(float64)
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyFields[9].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(func() time.Time)
	// apikeyDescUpdatedAt is the schema descriptor for updated_at field.
	apikeyDescUpdatedAt := apikeyFields[10].Descriptor()
	// apikey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apikey.DefaultUpdatedAt = apikeyDescUpdatedAt.Default.(func() time.Time)
	// apikey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	apikey.UpdateDefaultUpdatedAt = apikeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[0].Descriptor()
	// account.NameValidator is a validator for the "name" field. It is called by the builders before save.
	account.NameValidator = accountDescName.Validators[0].(func(string) error)
	// accountDescPlatform is the schema descriptor for platform field.
	accountDescPlatform := accountFields[1].Descriptor()
	// account.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	account.PlatformValidator = accountDescPlatform.Validators[0].(func(string) error)
	// accountDescType is the schema descriptor for type field.
	accountDescType := accountFields[2].Descriptor()
	// account.DefaultType holds the default value on creation for the type field.
	account.DefaultType = accountDescType.Default.(string)
	// accountDescCredentials is the schema descriptor for credentials field.
	accountDescCredentials := accountFields[3].Descriptor()
	// account.DefaultCredentials holds the default value on creation for the credentials field.
	account.DefaultCredentials = accountDescCredentials.Default.(map[string]string)
	// accountDescPriority is the schema descriptor for priority field.
	accountDescPriority := accountFields[5].Descriptor()
	// account.DefaultPriority holds the default value on creation for the priority field.
	account.DefaultPriority = accountDescPriority.Default.(int)
	// account.PriorityValidator is a validator for the "priority" field. It is called by the builders before save.
	account.PriorityValidator = func() func(int) error {
		validators := accountDescPriority.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(priority int) error {
			for _, fn := range fns {
				if err := fn(priority); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescMaxConcurrency is the schema descriptor for max_concurrency field.
	accountDescMaxConcurrency := accountFields[6].Descriptor()
	// account.DefaultMaxConcurrency holds the default value on creation for the max_concurrency field.
	account.DefaultMaxConcurrency = accountDescMaxConcurrency.Default.(int)
	// accountDescRateMultiplier is the schema descriptor for rate_multiplier field.
	accountDescRateMultiplier := accountFields[7].Descriptor()
	// account.DefaultRateMultiplier holds the default value on creation for the rate_multiplier field.
	account.DefaultRateMultiplier = accountDescRateMultiplier.Default.(float64)
	// accountDescErrorMsg is the schema descriptor for error_msg field.
	accountDescErrorMsg := accountFields[8].Descriptor()
	// account.DefaultErrorMsg holds the default value on creation for the error_msg field.
	account.DefaultErrorMsg = accountDescErrorMsg.Default.(string)
	// accountDescExtra is the schema descriptor for extra field.
	accountDescExtra := accountFields[10].Descriptor()
	// account.DefaultExtra holds the default value on creation for the extra field.
	account.DefaultExtra = accountDescExtra.Default.(map[string]interface{})
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[11].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountFields[12].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	balancelogFields := schema.BalanceLog{}.Fields()
	_ = balancelogFields
	// balancelogDescRemark is the schema descriptor for remark field.
	balancelogDescRemark := balancelogFields[4].Descriptor()
	// balancelog.DefaultRemark holds the default value on creation for the remark field.
	balancelog.DefaultRemark = balancelogDescRemark.Default.(string)
	// balancelogDescCreatedAt is the schema descriptor for created_at field.
	balancelogDescCreatedAt := balancelogFields[5].Descriptor()
	// balancelog.DefaultCreatedAt holds the default value on creation for the created_at field.
	balancelog.DefaultCreatedAt = balancelogDescCreatedAt.Default.(func() time.Time)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[0].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = groupDescName.Validators[0].(func(string) error)
	// groupDescPlatform is the schema descriptor for platform field.
	groupDescPlatform := groupFields[1].Descriptor()
	// group.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	group.PlatformValidator = groupDescPlatform.Validators[0].(func(string) error)
	// groupDescRateMultiplier is the schema descriptor for rate_multiplier field.
	groupDescRateMultiplier := groupFields[2].Descriptor()
	// group.DefaultRateMultiplier holds the default value on creation for the rate_multiplier field.
	group.DefaultRateMultiplier = groupDescRateMultiplier.Default.(float64)
	// groupDescIsExclusive is the schema descriptor for is_exclusive field.
	groupDescIsExclusive := groupFields[3].Descriptor()
	// group.DefaultIsExclusive holds the default value on creation for the is_exclusive field.
	group.DefaultIsExclusive = groupDescIsExclusive.Default.(bool)
	// groupDescServiceTier is the schema descriptor for service_tier field.
	groupDescServiceTier := groupFields[7].Descriptor()
	// group.DefaultServiceTier holds the default value on creation for the service_tier field.
	group.DefaultServiceTier = groupDescServiceTier.Default.(string)
	// groupDescSortWeight is the schema descriptor for sort_weight field.
	groupDescSortWeight := groupFields[8].Descriptor()
	// group.DefaultSortWeight holds the default value on creation for the sort_weight field.
	group.DefaultSortWeight = groupDescSortWeight.Default.(int)
	// groupDescCreatedAt is the schema descriptor for created_at field.
	groupDescCreatedAt := groupFields[9].Descriptor()
	// group.DefaultCreatedAt holds the default value on creation for the created_at field.
	group.DefaultCreatedAt = groupDescCreatedAt.Default.(func() time.Time)
	// groupDescUpdatedAt is the schema descriptor for updated_at field.
	groupDescUpdatedAt := groupFields[10].Descriptor()
	// group.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	group.DefaultUpdatedAt = groupDescUpdatedAt.Default.(func() time.Time)
	// group.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	group.UpdateDefaultUpdatedAt = groupDescUpdatedAt.UpdateDefault.(func() time.Time)
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescOrderNo is the schema descriptor for order_no field.
	orderDescOrderNo := orderFields[0].Descriptor()
	// order.OrderNoValidator is a validator for the "order_no" field. It is called by the builders before save.
	order.OrderNoValidator = orderDescOrderNo.Validators[0].(func(string) error)
	// orderDescChannel is the schema descriptor for channel field.
	orderDescChannel := orderFields[3].Descriptor()
	// order.DefaultChannel holds the default value on creation for the channel field.
	order.DefaultChannel = orderDescChannel.Default.(string)
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderFields[5].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescUpdatedAt is the schema descriptor for updated_at field.
	orderDescUpdatedAt := orderFields[6].Descriptor()
	// order.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	order.DefaultUpdatedAt = orderDescUpdatedAt.Default.(func() time.Time)
	// order.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	order.UpdateDefaultUpdatedAt = orderDescUpdatedAt.UpdateDefault.(func() time.Time)
	pluginFields := schema.Plugin{}.Fields()
	_ = pluginFields
	// pluginDescName is the schema descriptor for name field.
	pluginDescName := pluginFields[0].Descriptor()
	// plugin.NameValidator is a validator for the "name" field. It is called by the builders before save.
	plugin.NameValidator = pluginDescName.Validators[0].(func(string) error)
	// pluginDescPlatform is the schema descriptor for platform field.
	pluginDescPlatform := pluginFields[1].Descriptor()
	// plugin.DefaultPlatform holds the default value on creation for the platform field.
	plugin.DefaultPlatform = pluginDescPlatform.Default.(string)
	// pluginDescVersion is the schema descriptor for version field.
	pluginDescVersion := pluginFields[2].Descriptor()
	// plugin.DefaultVersion holds the default value on creation for the version field.
	plugin.DefaultVersion = pluginDescVersion.Default.(string)
	// pluginDescBinaryPath is the schema descriptor for binary_path field.
	pluginDescBinaryPath := pluginFields[6].Descriptor()
	// plugin.DefaultBinaryPath holds the default value on creation for the binary_path field.
	plugin.DefaultBinaryPath = pluginDescBinaryPath.Default.(string)
	// pluginDescCreatedAt is the schema descriptor for created_at field.
	pluginDescCreatedAt := pluginFields[7].Descriptor()
	// plugin.DefaultCreatedAt holds the default value on creation for the created_at field.
	plugin.DefaultCreatedAt = pluginDescCreatedAt.Default.(func() time.Time)
	// pluginDescUpdatedAt is the schema descriptor for updated_at field.
	pluginDescUpdatedAt := pluginFields[8].Descriptor()
	// plugin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	plugin.DefaultUpdatedAt = pluginDescUpdatedAt.Default.(func() time.Time)
	// plugin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	plugin.UpdateDefaultUpdatedAt = pluginDescUpdatedAt.UpdateDefault.(func() time.Time)
	pluginsourceFields := schema.PluginSource{}.Fields()
	_ = pluginsourceFields
	// pluginsourceDescName is the schema descriptor for name field.
	pluginsourceDescName := pluginsourceFields[0].Descriptor()
	// pluginsource.NameValidator is a validator for the "name" field. It is called by the builders before save.
	pluginsource.NameValidator = pluginsourceDescName.Validators[0].(func(string) error)
	// pluginsourceDescURL is the schema descriptor for url field.
	pluginsourceDescURL := pluginsourceFields[1].Descriptor()
	// pluginsource.URLValidator is a validator for the "url" field. It is called by the builders before save.
	pluginsource.URLValidator = pluginsourceDescURL.Validators[0].(func(string) error)
	// pluginsourceDescIsOfficial is the schema descriptor for is_official field.
	pluginsourceDescIsOfficial := pluginsourceFields[2].Descriptor()
	// pluginsource.DefaultIsOfficial holds the default value on creation for the is_official field.
	pluginsource.DefaultIsOfficial = pluginsourceDescIsOfficial.Default.(bool)
	// pluginsourceDescCreatedAt is the schema descriptor for created_at field.
	pluginsourceDescCreatedAt := pluginsourceFields[4].Descriptor()
	// pluginsource.DefaultCreatedAt holds the default value on creation for the created_at field.
	pluginsource.DefaultCreatedAt = pluginsourceDescCreatedAt.Default.(func() time.Time)
	// pluginsourceDescUpdatedAt is the schema descriptor for updated_at field.
	pluginsourceDescUpdatedAt := pluginsourceFields[5].Descriptor()
	// pluginsource.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pluginsource.DefaultUpdatedAt = pluginsourceDescUpdatedAt.Default.(func() time.Time)
	// pluginsource.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pluginsource.UpdateDefaultUpdatedAt = pluginsourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	proxyFields := schema.Proxy{}.Fields()
	_ = proxyFields
	// proxyDescName is the schema descriptor for name field.
	proxyDescName := proxyFields[0].Descriptor()
	// proxy.NameValidator is a validator for the "name" field. It is called by the builders before save.
	proxy.NameValidator = proxyDescName.Validators[0].(func(string) error)
	// proxyDescAddress is the schema descriptor for address field.
	proxyDescAddress := proxyFields[2].Descriptor()
	// proxy.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	proxy.AddressValidator = proxyDescAddress.Validators[0].(func(string) error)
	// proxyDescUsername is the schema descriptor for username field.
	proxyDescUsername := proxyFields[4].Descriptor()
	// proxy.DefaultUsername holds the default value on creation for the username field.
	proxy.DefaultUsername = proxyDescUsername.Default.(string)
	// proxyDescPassword is the schema descriptor for password field.
	proxyDescPassword := proxyFields[5].Descriptor()
	// proxy.DefaultPassword holds the default value on creation for the password field.
	proxy.DefaultPassword = proxyDescPassword.Default.(string)
	// proxyDescCreatedAt is the schema descriptor for created_at field.
	proxyDescCreatedAt := proxyFields[7].Descriptor()
	// proxy.DefaultCreatedAt holds the default value on creation for the created_at field.
	proxy.DefaultCreatedAt = proxyDescCreatedAt.Default.(func() time.Time)
	// proxyDescUpdatedAt is the schema descriptor for updated_at field.
	proxyDescUpdatedAt := proxyFields[8].Descriptor()
	// proxy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	proxy.DefaultUpdatedAt = proxyDescUpdatedAt.Default.(func() time.Time)
	// proxy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	proxy.UpdateDefaultUpdatedAt = proxyDescUpdatedAt.UpdateDefault.(func() time.Time)
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescKey is the schema descriptor for key field.
	settingDescKey := settingFields[0].Descriptor()
	// setting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	setting.KeyValidator = settingDescKey.Validators[0].(func(string) error)
	// settingDescValue is the schema descriptor for value field.
	settingDescValue := settingFields[1].Descriptor()
	// setting.DefaultValue holds the default value on creation for the value field.
	setting.DefaultValue = settingDescValue.Default.(string)
	// settingDescGroup is the schema descriptor for group field.
	settingDescGroup := settingFields[2].Descriptor()
	// setting.DefaultGroup holds the default value on creation for the group field.
	setting.DefaultGroup = settingDescGroup.Default.(string)
	// settingDescCreatedAt is the schema descriptor for created_at field.
	settingDescCreatedAt := settingFields[3].Descriptor()
	// setting.DefaultCreatedAt holds the default value on creation for the created_at field.
	setting.DefaultCreatedAt = settingDescCreatedAt.Default.(func() time.Time)
	// settingDescUpdatedAt is the schema descriptor for updated_at field.
	settingDescUpdatedAt := settingFields[4].Descriptor()
	// setting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	setting.DefaultUpdatedAt = settingDescUpdatedAt.Default.(func() time.Time)
	// setting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	setting.UpdateDefaultUpdatedAt = settingDescUpdatedAt.UpdateDefault.(func() time.Time)
	usagelogFields := schema.UsageLog{}.Fields()
	_ = usagelogFields
	// usagelogDescPlatform is the schema descriptor for platform field.
	usagelogDescPlatform := usagelogFields[0].Descriptor()
	// usagelog.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	usagelog.PlatformValidator = usagelogDescPlatform.Validators[0].(func(string) error)
	// usagelogDescModel is the schema descriptor for model field.
	usagelogDescModel := usagelogFields[1].Descriptor()
	// usagelog.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	usagelog.ModelValidator = usagelogDescModel.Validators[0].(func(string) error)
	// usagelogDescInputTokens is the schema descriptor for input_tokens field.
	usagelogDescInputTokens := usagelogFields[2].Descriptor()
	// usagelog.DefaultInputTokens holds the default value on creation for the input_tokens field.
	usagelog.DefaultInputTokens = usagelogDescInputTokens.Default.(int)
	// usagelogDescOutputTokens is the schema descriptor for output_tokens field.
	usagelogDescOutputTokens := usagelogFields[3].Descriptor()
	// usagelog.DefaultOutputTokens holds the default value on creation for the output_tokens field.
	usagelog.DefaultOutputTokens = usagelogDescOutputTokens.Default.(int)
	// usagelogDescCachedInputTokens is the schema descriptor for cached_input_tokens field.
	usagelogDescCachedInputTokens := usagelogFields[4].Descriptor()
	// usagelog.DefaultCachedInputTokens holds the default value on creation for the cached_input_tokens field.
	usagelog.DefaultCachedInputTokens = usagelogDescCachedInputTokens.Default.(int)
	// usagelogDescCacheTokens is the schema descriptor for cache_tokens field.
	usagelogDescCacheTokens := usagelogFields[5].Descriptor()
	// usagelog.DefaultCacheTokens holds the default value on creation for the cache_tokens field.
	usagelog.DefaultCacheTokens = usagelogDescCacheTokens.Default.(int)
	// usagelogDescReasoningOutputTokens is the schema descriptor for reasoning_output_tokens field.
	usagelogDescReasoningOutputTokens := usagelogFields[6].Descriptor()
	// usagelog.DefaultReasoningOutputTokens holds the default value on creation for the reasoning_output_tokens field.
	usagelog.DefaultReasoningOutputTokens = usagelogDescReasoningOutputTokens.Default.(int)
	// usagelogDescInputCost is the schema descriptor for input_cost field.
	usagelogDescInputCost := usagelogFields[7].Descriptor()
	// usagelog.DefaultInputCost holds the default value on creation for the input_cost field.
	usagelog.DefaultInputCost = usagelogDescInputCost.Default.(float64)
	// usagelogDescOutputCost is the schema descriptor for output_cost field.
	usagelogDescOutputCost := usagelogFields[8].Descriptor()
	// usagelog.DefaultOutputCost holds the default value on creation for the output_cost field.
	usagelog.DefaultOutputCost = usagelogDescOutputCost.Default.(float64)
	// usagelogDescCachedInputCost is the schema descriptor for cached_input_cost field.
	usagelogDescCachedInputCost := usagelogFields[9].Descriptor()
	// usagelog.DefaultCachedInputCost holds the default value on creation for the cached_input_cost field.
	usagelog.DefaultCachedInputCost = usagelogDescCachedInputCost.Default.(float64)
	// usagelogDescCacheCost is the schema descriptor for cache_cost field.
	usagelogDescCacheCost := usagelogFields[10].Descriptor()
	// usagelog.DefaultCacheCost holds the default value on creation for the cache_cost field.
	usagelog.DefaultCacheCost = usagelogDescCacheCost.Default.(float64)
	// usagelogDescTotalCost is the schema descriptor for total_cost field.
	usagelogDescTotalCost := usagelogFields[11].Descriptor()
	// usagelog.DefaultTotalCost holds the default value on creation for the total_cost field.
	usagelog.DefaultTotalCost = usagelogDescTotalCost.Default.(float64)
	// usagelogDescActualCost is the schema descriptor for actual_cost field.
	usagelogDescActualCost := usagelogFields[12].Descriptor()
	// usagelog.DefaultActualCost holds the default value on creation for the actual_cost field.
	usagelog.DefaultActualCost = usagelogDescActualCost.Default.(float64)
	// usagelogDescRateMultiplier is the schema descriptor for rate_multiplier field.
	usagelogDescRateMultiplier := usagelogFields[13].Descriptor()
	// usagelog.DefaultRateMultiplier holds the default value on creation for the rate_multiplier field.
	usagelog.DefaultRateMultiplier = usagelogDescRateMultiplier.Default.(float64)
	// usagelogDescAccountRateMultiplier is the schema descriptor for account_rate_multiplier field.
	usagelogDescAccountRateMultiplier := usagelogFields[14].Descriptor()
	// usagelog.DefaultAccountRateMultiplier holds the default value on creation for the account_rate_multiplier field.
	usagelog.DefaultAccountRateMultiplier = usagelogDescAccountRateMultiplier.Default.(float64)
	// usagelogDescServiceTier is the schema descriptor for service_tier field.
	usagelogDescServiceTier := usagelogFields[15].Descriptor()
	// usagelog.DefaultServiceTier holds the default value on creation for the service_tier field.
	usagelog.DefaultServiceTier = usagelogDescServiceTier.Default.(string)
	// usagelogDescStream is the schema descriptor for stream field.
	usagelogDescStream := usagelogFields[16].Descriptor()
	// usagelog.DefaultStream holds the default value on creation for the stream field.
	usagelog.DefaultStream = usagelogDescStream.Default.(bool)
	// usagelogDescDurationMs is the schema descriptor for duration_ms field.
	usagelogDescDurationMs := usagelogFields[17].Descriptor()
	// usagelog.DefaultDurationMs holds the default value on creation for the duration_ms field.
	usagelog.DefaultDurationMs = usagelogDescDurationMs.Default.(int64)
	// usagelogDescFirstTokenMs is the schema descriptor for first_token_ms field.
	usagelogDescFirstTokenMs := usagelogFields[18].Descriptor()
	// usagelog.DefaultFirstTokenMs holds the default value on creation for the first_token_ms field.
	usagelog.DefaultFirstTokenMs = usagelogDescFirstTokenMs.Default.(int64)
	// usagelogDescUserAgent is the schema descriptor for user_agent field.
	usagelogDescUserAgent := usagelogFields[19].Descriptor()
	// usagelog.DefaultUserAgent holds the default value on creation for the user_agent field.
	usagelog.DefaultUserAgent = usagelogDescUserAgent.Default.(string)
	// usagelogDescIPAddress is the schema descriptor for ip_address field.
	usagelogDescIPAddress := usagelogFields[20].Descriptor()
	// usagelog.DefaultIPAddress holds the default value on creation for the ip_address field.
	usagelog.DefaultIPAddress = usagelogDescIPAddress.Default.(string)
	// usagelogDescCreatedAt is the schema descriptor for created_at field.
	usagelogDescCreatedAt := usagelogFields[21].Descriptor()
	// usagelog.DefaultCreatedAt holds the default value on creation for the created_at field.
	usagelog.DefaultCreatedAt = usagelogDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[2].Descriptor()
	// user.DefaultUsername holds the default value on creation for the username field.
	user.DefaultUsername = userDescUsername.Default.(string)
	// userDescBalance is the schema descriptor for balance field.
	userDescBalance := userFields[3].Descriptor()
	// user.DefaultBalance holds the default value on creation for the balance field.
	user.DefaultBalance = userDescBalance.Default.(float64)
	// userDescMaxConcurrency is the schema descriptor for max_concurrency field.
	userDescMaxConcurrency := userFields[5].Descriptor()
	// user.DefaultMaxConcurrency holds the default value on creation for the max_concurrency field.
	user.DefaultMaxConcurrency = userDescMaxConcurrency.Default.(int)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[9].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[10].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	usersubscriptionFields := schema.UserSubscription{}.Fields()
	_ = usersubscriptionFields
	// usersubscriptionDescCreatedAt is the schema descriptor for created_at field.
	usersubscriptionDescCreatedAt := usersubscriptionFields[4].Descriptor()
	// usersubscription.DefaultCreatedAt holds the default value on creation for the created_at field.
	usersubscription.DefaultCreatedAt = usersubscriptionDescCreatedAt.Default.(func() time.Time)
	// usersubscriptionDescUpdatedAt is the schema descriptor for updated_at field.
	usersubscriptionDescUpdatedAt := usersubscriptionFields[5].Descriptor()
	// usersubscription.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	usersubscription.DefaultUpdatedAt = usersubscriptionDescUpdatedAt.Default.(func() time.Time)
	// usersubscription.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	usersubscription.UpdateDefaultUpdatedAt = usersubscriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
}
