// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/account"
	"github.com/DouDOU-start/airgate-core/ent/apikey"
	"github.com/DouDOU-start/airgate-core/ent/group"
	"github.com/DouDOU-start/airgate-core/ent/usagelog"
	"github.com/DouDOU-start/airgate-core/ent/user"
)

// UsageLogCreate is the builder for creating a UsageLog entity.
type UsageLogCreate struct {
	config
	mutation *UsageLogMutation
	hooks    []Hook
}

// SetPlatform sets the "platform" field.
func (ulc *UsageLogCreate) SetPlatform(s string) *UsageLogCreate {
	ulc.mutation.SetPlatform(s)
	return ulc
}

// SetModel sets the "model" field.
func (ulc *UsageLogCreate) SetModel(s string) *UsageLogCreate {
	ulc.mutation.SetModel(s)
	return ulc
}

// SetInputTokens sets the "input_tokens" field.
func (ulc *UsageLogCreate) SetInputTokens(i int) *UsageLogCreate {
	ulc.mutation.SetInputTokens(i)
	return ulc
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableInputTokens(i *int) *UsageLogCreate {
	if i != nil {
		ulc.SetInputTokens(*i)
	}
	return ulc
}

// SetOutputTokens sets the "output_tokens" field.
func (ulc *UsageLogCreate) SetOutputTokens(i int) *UsageLogCreate {
	ulc.mutation.SetOutputTokens(i)
	return ulc
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableOutputTokens(i *int) *UsageLogCreate {
	if i != nil {
		ulc.SetOutputTokens(*i)
	}
	return ulc
}

// SetCachedInputTokens sets the "cached_input_tokens" field.
func (ulc *UsageLogCreate) SetCachedInputTokens(i int) *UsageLogCreate {
	ulc.mutation.SetCachedInputTokens(i)
	return ulc
}

// SetNillableCachedInputTokens sets the "cached_input_tokens" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableCachedInputTokens(i *int) *UsageLogCreate {
	if i != nil {
		ulc.SetCachedInputTokens(*i)
	}
	return ulc
}

// SetCacheTokens sets the "cache_tokens" field.
func (ulc *UsageLogCreate) SetCacheTokens(i int) *UsageLogCreate {
	ulc.mutation.SetCacheTokens(i)
	return ulc
}

// SetNillableCacheTokens sets the "cache_tokens" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableCacheTokens(i *int) *UsageLogCreate {
	if i != nil {
		ulc.SetCacheTokens(*i)
	}
	return ulc
}

// SetReasoningOutputTokens sets the "reasoning_output_tokens" field.
func (ulc *UsageLogCreate) SetReasoningOutputTokens(i int) *UsageLogCreate {
	ulc.mutation.SetReasoningOutputTokens(i)
	return ulc
}

// SetNillableReasoningOutputTokens sets the "reasoning_output_tokens" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableReasoningOutputTokens(i *int) *UsageLogCreate {
	if i != nil {
		ulc.SetReasoningOutputTokens(*i)
	}
	return ulc
}

// SetInputCost sets the "input_cost" field.
func (ulc *UsageLogCreate) SetInputCost(f float64) *UsageLogCreate {
	ulc.mutation.SetInputCost(f)
	return ulc
}

// SetNillableInputCost sets the "input_cost" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableInputCost(f *float64) *UsageLogCreate {
	if f != nil {
		ulc.SetInputCost(*f)
	}
	return ulc
}

// SetOutputCost sets the "output_cost" field.
func (ulc *UsageLogCreate) SetOutputCost(f float64) *UsageLogCreate {
	ulc.mutation.SetOutputCost(f)
	return ulc
}

// SetNillableOutputCost sets the "output_cost" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableOutputCost(f *float64) *UsageLogCreate {
	if f != nil {
		ulc.SetOutputCost(*f)
	}
	return ulc
}

// SetCachedInputCost sets the "cached_input_cost" field.
func (ulc *UsageLogCreate) SetCachedInputCost(f float64) *UsageLogCreate {
	ulc.mutation.SetCachedInputCost(f)
	return ulc
}

// SetNillableCachedInputCost sets the "cached_input_cost" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableCachedInputCost(f *float64) *UsageLogCreate {
	if f != nil {
		ulc.SetCachedInputCost(*f)
	}
	return ulc
}

// SetCacheCost sets the "cache_cost" field.
func (ulc *UsageLogCreate) SetCacheCost(f float64) *UsageLogCreate {
	ulc.mutation.SetCacheCost(f)
	return ulc
}

// SetNillableCacheCost sets the "cache_cost" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableCacheCost(f *float64) *UsageLogCreate {
	if f != nil {
		ulc.SetCacheCost(*f)
	}
	return ulc
}

// SetTotalCost sets the "total_cost" field.
func (ulc *UsageLogCreate) SetTotalCost(f float64) *UsageLogCreate {
	ulc.mutation.SetTotalCost(f)
	return ulc
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableTotalCost(f *float64) *UsageLogCreate {
	if f != nil {
		ulc.SetTotalCost(*f)
	}
	return ulc
}

// SetActualCost sets the "actual_cost" field.
func (ulc *UsageLogCreate) SetActualCost(f float64) *UsageLogCreate {
	ulc.mutation.SetActualCost(f)
	return ulc
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableActualCost(f *float64) *UsageLogCreate {
	if f != nil {
		ulc.SetActualCost(*f)
	}
	return ulc
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (ulc *UsageLogCreate) SetRateMultiplier(f float64) *UsageLogCreate {
	ulc.mutation.SetRateMultiplier(f)
	return ulc
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableRateMultiplier(f *float64) *UsageLogCreate {
	if f != nil {
		ulc.SetRateMultiplier(*f)
	}
	return ulc
}

// SetAccountRateMultiplier sets the "account_rate_multiplier" field.
func (ulc *UsageLogCreate) SetAccountRateMultiplier(f float64) *UsageLogCreate {
	ulc.mutation.SetAccountRateMultiplier(f)
	return ulc
}

// SetNillableAccountRateMultiplier sets the "account_rate_multiplier" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableAccountRateMultiplier(f *float64) *UsageLogCreate {
	if f != nil {
		ulc.SetAccountRateMultiplier(*f)
	}
	return ulc
}

// SetServiceTier sets the "service_tier" field.
func (ulc *UsageLogCreate) SetServiceTier(s string) *UsageLogCreate {
	ulc.mutation.SetServiceTier(s)
	return ulc
}

// SetNillableServiceTier sets the "service_tier" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableServiceTier(s *string) *UsageLogCreate {
	if s != nil {
		ulc.SetServiceTier(*s)
	}
	return ulc
}

// SetStream sets the "stream" field.
func (ulc *UsageLogCreate) SetStream(b bool) *UsageLogCreate {
	ulc.mutation.SetStream(b)
	return ulc
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableStream(b *bool) *UsageLogCreate {
	if b != nil {
		ulc.SetStream(*b)
	}
	return ulc
}

// SetDurationMs sets the "duration_ms" field.
func (ulc *UsageLogCreate) SetDurationMs(i int64) *UsageLogCreate {
	ulc.mutation.SetDurationMs(i)
	return ulc
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableDurationMs(i *int64) *UsageLogCreate {
	if i != nil {
		ulc.SetDurationMs(*i)
	}
	return ulc
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (ulc *UsageLogCreate) SetFirstTokenMs(i int64) *UsageLogCreate {
	ulc.mutation.SetFirstTokenMs(i)
	return ulc
}

// SetNillableFirstTokenMs sets the "first_token_ms" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableFirstTokenMs(i *int64) *UsageLogCreate {
	if i != nil {
		ulc.SetFirstTokenMs(*i)
	}
	return ulc
}

// SetUserAgent sets the "user_agent" field.
func (ulc *UsageLogCreate) SetUserAgent(s string) *UsageLogCreate {
	ulc.mutation.SetUserAgent(s)
	return ulc
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableUserAgent(s *string) *UsageLogCreate {
	if s != nil {
		ulc.SetUserAgent(*s)
	}
	return ulc
}

// SetIPAddress sets the "ip_address" field.
func (ulc *UsageLogCreate) SetIPAddress(s string) *UsageLogCreate {
	ulc.mutation.SetIPAddress(s)
	return ulc
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableIPAddress(s *string) *UsageLogCreate {
	if s != nil {
		ulc.SetIPAddress(*s)
	}
	return ulc
}

// SetCreatedAt sets the "created_at" field.
func (ulc *UsageLogCreate) SetCreatedAt(t time.Time) *UsageLogCreate {
	ulc.mutation.SetCreatedAt(t)
	return ulc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableCreatedAt(t *time.Time) *UsageLogCreate {
	if t != nil {
		ulc.SetCreatedAt(*t)
	}
	return ulc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ulc *UsageLogCreate) SetUserID(id int) *UsageLogCreate {
	ulc.mutation.SetUserID(id)
	return ulc
}

// SetUser sets the "user" edge to the User entity.
func (ulc *UsageLogCreate) SetUser(u *User) *UsageLogCreate {
	return ulc.SetUserID(u.ID)
}

// SetAPIKeyID sets the "api_key" edge to the APIKey entity by ID.
func (ulc *UsageLogCreate) SetAPIKeyID(id int) *UsageLogCreate {
	ulc.mutation.SetAPIKeyID(id)
	return ulc
}

// SetNillableAPIKeyID sets the "api_key" edge to the APIKey entity by ID if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableAPIKeyID(id *int) *UsageLogCreate {
	if id != nil {
		ulc = ulc.SetAPIKeyID(*id)
	}
	return ulc
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (ulc *UsageLogCreate) SetAPIKey(a *APIKey) *UsageLogCreate {
	return ulc.SetAPIKeyID(a.ID)
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (ulc *UsageLogCreate) SetAccountID(id int) *UsageLogCreate {
	ulc.mutation.SetAccountID(id)
	return ulc
}

// SetAccount sets the "account" edge to the Account entity.
func (ulc *UsageLogCreate) SetAccount(a *Account) *UsageLogCreate {
	return ulc.SetAccountID(a.ID)
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (ulc *UsageLogCreate) SetGroupID(id int) *UsageLogCreate {
	ulc.mutation.SetGroupID(id)
	return ulc
}

// SetNillableGroupID sets the "group" edge to the Group entity by ID if the given value is not nil.
func (ulc *UsageLogCreate) SetNillableGroupID(id *int) *UsageLogCreate {
	if id != nil {
		ulc = ulc.SetGroupID(*id)
	}
	return ulc
}

// SetGroup sets the "group" edge to the Group entity.
func (ulc *UsageLogCreate) SetGroup(g *Group) *UsageLogCreate {
	return ulc.SetGroupID(g.ID)
}

// Mutation returns the UsageLogMutation object of the builder.
func (ulc *UsageLogCreate) Mutation() *UsageLogMutation {
	return ulc.mutation
}

// Save creates the UsageLog in the database.
func (ulc *UsageLogCreate) Save(ctx context.Context) (*UsageLog, error) {
	ulc.defaults()
	return withHooks(ctx, ulc.sqlSave, ulc.mutation, ulc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ulc *UsageLogCreate) SaveX(ctx context.Context) *UsageLog {
	v, err := ulc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ulc *UsageLogCreate) Exec(ctx context.Context) error {
	_, err := ulc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ulc *UsageLogCreate) ExecX(ctx context.Context) {
	if err := ulc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ulc *UsageLogCreate) defaults() {
	if _, ok := ulc.mutation.InputTokens(); !ok {
		v := usagelog.DefaultInputTokens
		ulc.mutation.SetInputTokens(v)
	}
	if _, ok := ulc.mutation.OutputTokens(); !ok {
		v := usagelog.DefaultOutputTokens
		ulc.mutation.SetOutputTokens(v)
	}
	if _, ok := ulc.mutation.CachedInputTokens(); !ok {
		v := usagelog.DefaultCachedInputTokens
		ulc.mutation.SetCachedInputTokens(v)
	}
	if _, ok := ulc.mutation.CacheTokens(); !ok {
		v := usagelog.DefaultCacheTokens
		ulc.mutation.SetCacheTokens(v)
	}
	if _, ok := ulc.mutation.ReasoningOutputTokens(); !ok {
		v := usagelog.DefaultReasoningOutputTokens
		ulc.mutation.SetReasoningOutputTokens(v)
	}
	if _, ok := ulc.mutation.InputCost(); !ok {
		v := usagelog.DefaultInputCost
		ulc.mutation.SetInputCost(v)
	}
	if _, ok := ulc.mutation.OutputCost(); !ok {
		v := usagelog.DefaultOutputCost
		ulc.mutation.SetOutputCost(v)
	}
	if _, ok := ulc.mutation.CachedInputCost(); !ok {
		v := usagelog.DefaultCachedInputCost
		ulc.mutation.SetCachedInputCost(v)
	}
	if _, ok := ulc.mutation.CacheCost(); !ok {
		v := usagelog.DefaultCacheCost
		ulc.mutation.SetCacheCost(v)
	}
	if _, ok := ulc.mutation.TotalCost(); !ok {
		v := usagelog.DefaultTotalCost
		ulc.mutation.SetTotalCost(v)
	}
	if _, ok := ulc.mutation.ActualCost(); !ok {
		v := usagelog.DefaultActualCost
		ulc.mutation.SetActualCost(v)
	}
	if _, ok := ulc.mutation.RateMultiplier(); !ok {
		v := usagelog.DefaultRateMultiplier
		ulc.mutation.SetRateMultiplier(v)
	}
	if _, ok := ulc.mutation.AccountRateMultiplier(); !ok {
		v := usagelog.DefaultAccountRateMultiplier
		ulc.mutation.SetAccountRateMultiplier(v)
	}
	if _, ok := ulc.mutation.ServiceTier(); !ok {
		v := usagelog.DefaultServiceTier
		ulc.mutation.SetServiceTier(v)
	}
	if _, ok := ulc.mutation.Stream(); !ok {
		v := usagelog.DefaultStream
		ulc.mutation.SetStream(v)
	}
	if _, ok := ulc.mutation.DurationMs(); !ok {
		v := usagelog.DefaultDurationMs
		ulc.mutation.SetDurationMs(v)
	}
	if _, ok := ulc.mutation.FirstTokenMs(); !ok {
		v := usagelog.DefaultFirstTokenMs
		ulc.mutation.SetFirstTokenMs(v)
	}
	if _, ok := ulc.mutation.UserAgent(); !ok {
		v := usagelog.DefaultUserAgent
		ulc.mutation.SetUserAgent(v)
	}
	if _, ok := ulc.mutation.IPAddress(); !ok {
		v := usagelog.DefaultIPAddress
		ulc.mutation.SetIPAddress(v)
	}
	if _, ok := ulc.mutation.CreatedAt(); !ok {
		v := usagelog.DefaultCreatedAt()
		ulc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ulc *UsageLogCreate) check() error {
	if _, ok := ulc.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "UsageLog.platform"`)}
	}
	if v, ok := ulc.mutation.Platform(); ok {
		if err := usagelog.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UsageLog.platform": %w`, err)}
		}
	}
	if _, ok := ulc.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "UsageLog.model"`)}
	}
	if v, ok := ulc.mutation.Model(); ok {
		if err := usagelog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "UsageLog.model": %w`, err)}
		}
	}
	if _, ok := ulc.mutation.InputTokens(); !ok {
		return &ValidationError{Name: "input_tokens", err: errors.New(`ent: missing required field "UsageLog.input_tokens"`)}
	}
	if _, ok := ulc.mutation.OutputTokens(); !ok {
		return &ValidationError{Name: "output_tokens", err: errors.New(`ent: missing required field "UsageLog.output_tokens"`)}
	}
	if _, ok := ulc.mutation.CachedInputTokens(); !ok {
		return &ValidationError{Name: "cached_input_tokens", err: errors.New(`ent: missing required field "UsageLog.cached_input_tokens"`)}
	}
	if _, ok := ulc.mutation.CacheTokens(); !ok {
		return &ValidationError{Name: "cache_tokens", err: errors.New(`ent: missing required field "UsageLog.cache_tokens"`)}
	}
	if _, ok := ulc.mutation.ReasoningOutputTokens(); !ok {
		return &ValidationError{Name: "reasoning_output_tokens", err: errors.New(`ent: missing required field "UsageLog.reasoning_output_tokens"`)}
	}
	if _, ok := ulc.mutation.InputCost(); !ok {
		return &ValidationError{Name: "input_cost", err: errors.New(`ent: missing required field "UsageLog.input_cost"`)}
	}
	if _, ok := ulc.mutation.OutputCost(); !ok {
		return &ValidationError{Name: "output_cost", err: errors.New(`ent: missing required field "UsageLog.output_cost"`)}
	}
	if _, ok := ulc.mutation.CachedInputCost(); !ok {
		return &ValidationError{Name: "cached_input_cost", err: errors.New(`ent: missing required field "UsageLog.cached_input_cost"`)}
	}
	if _, ok := ulc.mutation.CacheCost(); !ok {
		return &ValidationError{Name: "cache_cost", err: errors.New(`ent: missing required field "UsageLog.cache_cost"`)}
	}
	if _, ok := ulc.mutation.TotalCost(); !ok {
		return &ValidationError{Name: "total_cost", err: errors.New(`ent: missing required field "UsageLog.total_cost"`)}
	}
	if _, ok := ulc.mutation.ActualCost(); !ok {
		return &ValidationError{Name: "actual_cost", err: errors.New(`ent: missing required field "UsageLog.actual_cost"`)}
	}
	if _, ok := ulc.mutation.RateMultiplier(); !ok {
		return &ValidationError{Name: "rate_multiplier", err: errors.New(`ent: missing required field "UsageLog.rate_multiplier"`)}
	}
	if _, ok := ulc.mutation.AccountRateMultiplier(); !ok {
		return &ValidationError{Name: "account_rate_multiplier", err: errors.New(`ent: missing required field "UsageLog.account_rate_multiplier"`)}
	}
	if _, ok := ulc.mutation.ServiceTier(); !ok {
		return &ValidationError{Name: "service_tier", err: errors.New(`ent: missing required field "UsageLog.service_tier"`)}
	}
	if _, ok := ulc.mutation.Stream(); !ok {
		return &ValidationError{Name: "stream", err: errors.New(`ent: missing required field "UsageLog.stream"`)}
	}
	if _, ok := ulc.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "UsageLog.duration_ms"`)}
	}
	if _, ok := ulc.mutation.FirstTokenMs(); !ok {
		return &ValidationError{Name: "first_token_ms", err: errors.New(`ent: missing required field "UsageLog.first_token_ms"`)}
	}
	if _, ok := ulc.mutation.UserAgent(); !ok {
		return &ValidationError{Name: "user_agent", err: errors.New(`ent: missing required field "UsageLog.user_agent"`)}
	}
	if _, ok := ulc.mutation.IPAddress(); !ok {
		return &ValidationError{Name: "ip_address", err: errors.New(`ent: missing required field "UsageLog.ip_address"`)}
	}
	if _, ok := ulc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageLog.created_at"`)}
	}
	if _, ok := ulc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UsageLog.user"`)}
	}
	if _, ok := ulc.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "UsageLog.account"`)}
	}
	return nil
}

func (ulc *UsageLogCreate) sqlSave(ctx context.Context) (*UsageLog, error) {
	if err := ulc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ulc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ulc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ulc.mutation.id = &_node.ID
	ulc.mutation.done = true
	return _node, nil
}

func (ulc *UsageLogCreate) createSpec() (*UsageLog, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageLog{config: ulc.config}
		_spec = sqlgraph.NewCreateSpec(usagelog.Table, sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt))
	)
	if value, ok := ulc.mutation.Platform(); ok {
		_spec.SetField(usagelog.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := ulc.mutation.Model(); ok {
		_spec.SetField(usagelog.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := ulc.mutation.InputTokens(); ok {
		_spec.SetField(usagelog.FieldInputTokens, field.TypeInt, value)
		_node.InputTokens = value
	}
	if value, ok := ulc.mutation.OutputTokens(); ok {
		_spec.SetField(usagelog.FieldOutputTokens, field.TypeInt, value)
		_node.OutputTokens = value
	}
	if value, ok := ulc.mutation.CachedInputTokens(); ok {
		_spec.SetField(usagelog.FieldCachedInputTokens, field.TypeInt, value)
		_node.CachedInputTokens = value
	}
	if value, ok := ulc.mutation.CacheTokens(); ok {
		_spec.SetField(usagelog.FieldCacheTokens, field.TypeInt, value)
		_node.CacheTokens = value
	}
	if value, ok := ulc.mutation.ReasoningOutputTokens(); ok {
		_spec.SetField(usagelog.FieldReasoningOutputTokens, field.TypeInt, value)
		_node.ReasoningOutputTokens = value
	}
	if value, ok := ulc.mutation.InputCost(); ok {
		_spec.SetField(usagelog.FieldInputCost, field.TypeFloat64, value)
		_node.InputCost = value
	}
	if value, ok := ulc.mutation.OutputCost(); ok {
		_spec.SetField(usagelog.FieldOutputCost, field.TypeFloat64, value)
		_node.OutputCost = value
	}
	if value, ok := ulc.mutation.CachedInputCost(); ok {
		_spec.SetField(usagelog.FieldCachedInputCost, field.TypeFloat64, value)
		_node.CachedInputCost = value
	}
	if value, ok := ulc.mutation.CacheCost(); ok {
		_spec.SetField(usagelog.FieldCacheCost, field.TypeFloat64, value)
		_node.CacheCost = value
	}
	if value, ok := ulc.mutation.TotalCost(); ok {
		_spec.SetField(usagelog.FieldTotalCost, field.TypeFloat64, value)
		_node.TotalCost = value
	}
	if value, ok := ulc.mutation.ActualCost(); ok {
		_spec.SetField(usagelog.FieldActualCost, field.TypeFloat64, value)
		_node.ActualCost = value
	}
	if value, ok := ulc.mutation.RateMultiplier(); ok {
		_spec.SetField(usagelog.FieldRateMultiplier, field.TypeFloat64, value)
		_node.RateMultiplier = value
	}
	if value, ok := ulc.mutation.AccountRateMultiplier(); ok {
		_spec.SetField(usagelog.FieldAccountRateMultiplier, field.TypeFloat64, value)
		_node.AccountRateMultiplier = value
	}
	if value, ok := ulc.mutation.ServiceTier(); ok {
		_spec.SetField(usagelog.FieldServiceTier, field.TypeString, value)
		_node.ServiceTier = value
	}
	if value, ok := ulc.mutation.Stream(); ok {
		_spec.SetField(usagelog.FieldStream, field.TypeBool, value)
		_node.Stream = value
	}
	if value, ok := ulc.mutation.DurationMs(); ok {
		_spec.SetField(usagelog.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := ulc.mutation.FirstTokenMs(); ok {
		_spec.SetField(usagelog.FieldFirstTokenMs, field.TypeInt64, value)
		_node.FirstTokenMs = value
	}
	if value, ok := ulc.mutation.UserAgent(); ok {
		_spec.SetField(usagelog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := ulc.mutation.IPAddress(); ok {
		_spec.SetField(usagelog.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := ulc.mutation.CreatedAt(); ok {
		_spec.SetField(usagelog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := ulc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.UserTable,
			Columns: []string{usagelog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_usage_logs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ulc.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.APIKeyTable,
			Columns: []string{usagelog.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.api_key_usage_logs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ulc.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.AccountTable,
			Columns: []string{usagelog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.account_usage_logs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ulc.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.GroupTable,
			Columns: []string{usagelog.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.group_usage_logs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UsageLogCreateBulk is the builder for creating many UsageLog entities in bulk.
type UsageLogCreateBulk struct {
	config
	err      error
	builders []*UsageLogCreate
}

// Save creates the UsageLog entities in the database.
func (ulcb *UsageLogCreateBulk) Save(ctx context.Context) ([]*UsageLog, error) {
	if ulcb.err != nil {
		return nil, ulcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ulcb.builders))
	nodes := make([]*UsageLog, len(ulcb.builders))
	mutators := make([]Mutator, len(ulcb.builders))
	for i := range ulcb.builders {
		func(i int, root context.Context) {
			builder := ulcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ulcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ulcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ulcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ulcb *UsageLogCreateBulk) SaveX(ctx context.Context) []*UsageLog {
	v, err := ulcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ulcb *UsageLogCreateBulk) Exec(ctx context.Context) error {
	_, err := ulcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ulcb *UsageLogCreateBulk) ExecX(ctx context.Context) {
	if err := ulcb.Exec(ctx); err != nil {
		panic(err)
	}
}
