// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/account"
	"github.com/DouDOU-start/airgate-core/ent/apikey"
	"github.com/DouDOU-start/airgate-core/ent/group"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
	"github.com/DouDOU-start/airgate-core/ent/usagelog"
	"github.com/DouDOU-start/airgate-core/ent/user"
)

// UsageLogUpdate is the builder for updating UsageLog entities.
type UsageLogUpdate struct {
	config
	hooks    []Hook
	mutation *UsageLogMutation
}

// Where appends a list predicates to the UsageLogUpdate builder.
func (ulu *UsageLogUpdate) Where(ps ...predicate.UsageLog) *UsageLogUpdate {
	ulu.mutation.Where(ps...)
	return ulu
}

// SetPlatform sets the "platform" field.
func (ulu *UsageLogUpdate) SetPlatform(s string) *UsageLogUpdate {
	ulu.mutation.SetPlatform(s)
	return ulu
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillablePlatform(s *string) *UsageLogUpdate {
	if s != nil {
		ulu.SetPlatform(*s)
	}
	return ulu
}

// SetModel sets the "model" field.
func (ulu *UsageLogUpdate) SetModel(s string) *UsageLogUpdate {
	ulu.mutation.SetModel(s)
	return ulu
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableModel(s *string) *UsageLogUpdate {
	if s != nil {
		ulu.SetModel(*s)
	}
	return ulu
}

// SetInputTokens sets the "input_tokens" field.
func (ulu *UsageLogUpdate) SetInputTokens(i int) *UsageLogUpdate {
	ulu.mutation.ResetInputTokens()
	ulu.mutation.SetInputTokens(i)
	return ulu
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableInputTokens(i *int) *UsageLogUpdate {
	if i != nil {
		ulu.SetInputTokens(*i)
	}
	return ulu
}

// AddInputTokens adds i to the "input_tokens" field.
func (ulu *UsageLogUpdate) AddInputTokens(i int) *UsageLogUpdate {
	ulu.mutation.AddInputTokens(i)
	return ulu
}

// SetOutputTokens sets the "output_tokens" field.
func (ulu *UsageLogUpdate) SetOutputTokens(i int) *UsageLogUpdate {
	ulu.mutation.ResetOutputTokens()
	ulu.mutation.SetOutputTokens(i)
	return ulu
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableOutputTokens(i *int) *UsageLogUpdate {
	if i != nil {
		ulu.SetOutputTokens(*i)
	}
	return ulu
}

// AddOutputTokens adds i to the "output_tokens" field.
func (ulu *UsageLogUpdate) AddOutputTokens(i int) *UsageLogUpdate {
	ulu.mutation.AddOutputTokens(i)
	return ulu
}

// SetCachedInputTokens sets the "cached_input_tokens" field.
func (ulu *UsageLogUpdate) SetCachedInputTokens(i int) *UsageLogUpdate {
	ulu.mutation.ResetCachedInputTokens()
	ulu.mutation.SetCachedInputTokens(i)
	return ulu
}

// SetNillableCachedInputTokens sets the "cached_input_tokens" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableCachedInputTokens(i *int) *UsageLogUpdate {
	if i != nil {
		ulu.SetCachedInputTokens(*i)
	}
	return ulu
}

// AddCachedInputTokens adds i to the "cached_input_tokens" field.
func (ulu *UsageLogUpdate) AddCachedInputTokens(i int) *UsageLogUpdate {
	ulu.mutation.AddCachedInputTokens(i)
	return ulu
}

// SetCacheTokens sets the "cache_tokens" field.
func (ulu *UsageLogUpdate) SetCacheTokens(i int) *UsageLogUpdate {
	ulu.mutation.ResetCacheTokens()
	ulu.mutation.SetCacheTokens(i)
	return ulu
}

// SetNillableCacheTokens sets the "cache_tokens" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableCacheTokens(i *int) *UsageLogUpdate {
	if i != nil {
		ulu.SetCacheTokens(*i)
	}
	return ulu
}

// AddCacheTokens adds i to the "cache_tokens" field.
func (ulu *UsageLogUpdate) AddCacheTokens(i int) *UsageLogUpdate {
	ulu.mutation.AddCacheTokens(i)
	return ulu
}

// SetReasoningOutputTokens sets the "reasoning_output_tokens" field.
func (ulu *UsageLogUpdate) SetReasoningOutputTokens(i int) *UsageLogUpdate {
	ulu.mutation.ResetReasoningOutputTokens()
	ulu.mutation.SetReasoningOutputTokens(i)
	return ulu
}

// SetNillableReasoningOutputTokens sets the "reasoning_output_tokens" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableReasoningOutputTokens(i *int) *UsageLogUpdate {
	if i != nil {
		ulu.SetReasoningOutputTokens(*i)
	}
	return ulu
}

// AddReasoningOutputTokens adds i to the "reasoning_output_tokens" field.
func (ulu *UsageLogUpdate) AddReasoningOutputTokens(i int) *UsageLogUpdate {
	ulu.mutation.AddReasoningOutputTokens(i)
	return ulu
}

// SetInputCost sets the "input_cost" field.
func (ulu *UsageLogUpdate) SetInputCost(f float64) *UsageLogUpdate {
	ulu.mutation.ResetInputCost()
	ulu.mutation.SetInputCost(f)
	return ulu
}

// SetNillableInputCost sets the "input_cost" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableInputCost(f *float64) *UsageLogUpdate {
	if f != nil {
		ulu.SetInputCost(*f)
	}
	return ulu
}

// AddInputCost adds f to the "input_cost" field.
func (ulu *UsageLogUpdate) AddInputCost(f float64) *UsageLogUpdate {
	ulu.mutation.AddInputCost(f)
	return ulu
}

// SetOutputCost sets the "output_cost" field.
func (ulu *UsageLogUpdate) SetOutputCost(f float64) *UsageLogUpdate {
	ulu.mutation.ResetOutputCost()
	ulu.mutation.SetOutputCost(f)
	return ulu
}

// SetNillableOutputCost sets the "output_cost" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableOutputCost(f *float64) *UsageLogUpdate {
	if f != nil {
		ulu.SetOutputCost(*f)
	}
	return ulu
}

// AddOutputCost adds f to the "output_cost" field.
func (ulu *UsageLogUpdate) AddOutputCost(f float64) *UsageLogUpdate {
	ulu.mutation.AddOutputCost(f)
	return ulu
}

// SetCachedInputCost sets the "cached_input_cost" field.
func (ulu *UsageLogUpdate) SetCachedInputCost(f float64) *UsageLogUpdate {
	ulu.mutation.ResetCachedInputCost()
	ulu.mutation.SetCachedInputCost(f)
	return ulu
}

// SetNillableCachedInputCost sets the "cached_input_cost" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableCachedInputCost(f *float64) *UsageLogUpdate {
	if f != nil {
		ulu.SetCachedInputCost(*f)
	}
	return ulu
}

// AddCachedInputCost adds f to the "cached_input_cost" field.
func (ulu *UsageLogUpdate) AddCachedInputCost(f float64) *UsageLogUpdate {
	ulu.mutation.AddCachedInputCost(f)
	return ulu
}

// SetCacheCost sets the "cache_cost" field.
func (ulu *UsageLogUpdate) SetCacheCost(f float64) *UsageLogUpdate {
	ulu.mutation.ResetCacheCost()
	ulu.mutation.SetCacheCost(f)
	return ulu
}

// SetNillableCacheCost sets the "cache_cost" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableCacheCost(f *float64) *UsageLogUpdate {
	if f != nil {
		ulu.SetCacheCost(*f)
	}
	return ulu
}

// AddCacheCost adds f to the "cache_cost" field.
func (ulu *UsageLogUpdate) AddCacheCost(f float64) *UsageLogUpdate {
	ulu.mutation.AddCacheCost(f)
	return ulu
}

// SetTotalCost sets the "total_cost" field.
func (ulu *UsageLogUpdate) SetTotalCost(f float64) *UsageLogUpdate {
	ulu.mutation.ResetTotalCost()
	ulu.mutation.SetTotalCost(f)
	return ulu
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableTotalCost(f *float64) *UsageLogUpdate {
	if f != nil {
		ulu.SetTotalCost(*f)
	}
	return ulu
}

// AddTotalCost adds f to the "total_cost" field.
func (ulu *UsageLogUpdate) AddTotalCost(f float64) *UsageLogUpdate {
	ulu.mutation.AddTotalCost(f)
	return ulu
}

// SetActualCost sets the "actual_cost" field.
func (ulu *UsageLogUpdate) SetActualCost(f float64) *UsageLogUpdate {
	ulu.mutation.ResetActualCost()
	ulu.mutation.SetActualCost(f)
	return ulu
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableActualCost(f *float64) *UsageLogUpdate {
	if f != nil {
		ulu.SetActualCost(*f)
	}
	return ulu
}

// AddActualCost adds f to the "actual_cost" field.
func (ulu *UsageLogUpdate) AddActualCost(f float64) *UsageLogUpdate {
	ulu.mutation.AddActualCost(f)
	return ulu
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (ulu *UsageLogUpdate) SetRateMultiplier(f float64) *UsageLogUpdate {
	ulu.mutation.ResetRateMultiplier()
	ulu.mutation.SetRateMultiplier(f)
	return ulu
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableRateMultiplier(f *float64) *UsageLogUpdate {
	if f != nil {
		ulu.SetRateMultiplier(*f)
	}
	return ulu
}

// AddRateMultiplier adds f to the "rate_multiplier" field.
func (ulu *UsageLogUpdate) AddRateMultiplier(f float64) *UsageLogUpdate {
	ulu.mutation.AddRateMultiplier(f)
	return ulu
}

// SetAccountRateMultiplier sets the "account_rate_multiplier" field.
func (ulu *UsageLogUpdate) SetAccountRateMultiplier(f float64) *UsageLogUpdate {
	ulu.mutation.ResetAccountRateMultiplier()
	ulu.mutation.SetAccountRateMultiplier(f)
	return ulu
}

// SetNillableAccountRateMultiplier sets the "account_rate_multiplier" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableAccountRateMultiplier(f *float64) *UsageLogUpdate {
	if f != nil {
		ulu.SetAccountRateMultiplier(*f)
	}
	return ulu
}

// AddAccountRateMultiplier adds f to the "account_rate_multiplier" field.
func (ulu *UsageLogUpdate) AddAccountRateMultiplier(f float64) *UsageLogUpdate {
	ulu.mutation.AddAccountRateMultiplier(f)
	return ulu
}

// SetServiceTier sets the "service_tier" field.
func (ulu *UsageLogUpdate) SetServiceTier(s string) *UsageLogUpdate {
	ulu.mutation.SetServiceTier(s)
	return ulu
}

// SetNillableServiceTier sets the "service_tier" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableServiceTier(s *string) *UsageLogUpdate {
	if s != nil {
		ulu.SetServiceTier(*s)
	}
	return ulu
}

// SetStream sets the "stream" field.
func (ulu *UsageLogUpdate) SetStream(b bool) *UsageLogUpdate {
	ulu.mutation.SetStream(b)
	return ulu
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableStream(b *bool) *UsageLogUpdate {
	if b != nil {
		ulu.SetStream(*b)
	}
	return ulu
}

// SetDurationMs sets the "duration_ms" field.
func (ulu *UsageLogUpdate) SetDurationMs(i int64) *UsageLogUpdate {
	ulu.mutation.ResetDurationMs()
	ulu.mutation.SetDurationMs(i)
	return ulu
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableDurationMs(i *int64) *UsageLogUpdate {
	if i != nil {
		ulu.SetDurationMs(*i)
	}
	return ulu
}

// AddDurationMs adds i to the "duration_ms" field.
func (ulu *UsageLogUpdate) AddDurationMs(i int64) *UsageLogUpdate {
	ulu.mutation.AddDurationMs(i)
	return ulu
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (ulu *UsageLogUpdate) SetFirstTokenMs(i int64) *UsageLogUpdate {
	ulu.mutation.ResetFirstTokenMs()
	ulu.mutation.SetFirstTokenMs(i)
	return ulu
}

// SetNillableFirstTokenMs sets the "first_token_ms" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableFirstTokenMs(i *int64) *UsageLogUpdate {
	if i != nil {
		ulu.SetFirstTokenMs(*i)
	}
	return ulu
}

// AddFirstTokenMs adds i to the "first_token_ms" field.
func (ulu *UsageLogUpdate) AddFirstTokenMs(i int64) *UsageLogUpdate {
	ulu.mutation.AddFirstTokenMs(i)
	return ulu
}

// SetUserAgent sets the "user_agent" field.
func (ulu *UsageLogUpdate) SetUserAgent(s string) *UsageLogUpdate {
	ulu.mutation.SetUserAgent(s)
	return ulu
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableUserAgent(s *string) *UsageLogUpdate {
	if s != nil {
		ulu.SetUserAgent(*s)
	}
	return ulu
}

// SetIPAddress sets the "ip_address" field.
func (ulu *UsageLogUpdate) SetIPAddress(s string) *UsageLogUpdate {
	ulu.mutation.SetIPAddress(s)
	return ulu
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableIPAddress(s *string) *UsageLogUpdate {
	if s != nil {
		ulu.SetIPAddress(*s)
	}
	return ulu
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ulu *UsageLogUpdate) SetUserID(id int) *UsageLogUpdate {
	ulu.mutation.SetUserID(id)
	return ulu
}

// SetUser sets the "user" edge to the User entity.
func (ulu *UsageLogUpdate) SetUser(u *User) *UsageLogUpdate {
	return ulu.SetUserID(u.ID)
}

// SetAPIKeyID sets the "api_key" edge to the APIKey entity by ID.
func (ulu *UsageLogUpdate) SetAPIKeyID(id int) *UsageLogUpdate {
	ulu.mutation.SetAPIKeyID(id)
	return ulu
}

// SetNillableAPIKeyID sets the "api_key" edge to the APIKey entity by ID if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableAPIKeyID(id *int) *UsageLogUpdate {
	if id != nil {
		ulu = ulu.SetAPIKeyID(*id)
	}
	return ulu
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (ulu *UsageLogUpdate) SetAPIKey(a *APIKey) *UsageLogUpdate {
	return ulu.SetAPIKeyID(a.ID)
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (ulu *UsageLogUpdate) SetAccountID(id int) *UsageLogUpdate {
	ulu.mutation.SetAccountID(id)
	return ulu
}

// SetAccount sets the "account" edge to the Account entity.
func (ulu *UsageLogUpdate) SetAccount(a *Account) *UsageLogUpdate {
	return ulu.SetAccountID(a.ID)
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (ulu *UsageLogUpdate) SetGroupID(id int) *UsageLogUpdate {
	ulu.mutation.SetGroupID(id)
	return ulu
}

// SetNillableGroupID sets the "group" edge to the Group entity by ID if the given value is not nil.
func (ulu *UsageLogUpdate) SetNillableGroupID(id *int) *UsageLogUpdate {
	if id != nil {
		ulu = ulu.SetGroupID(*id)
	}
	return ulu
}

// SetGroup sets the "group" edge to the Group entity.
func (ulu *UsageLogUpdate) SetGroup(g *Group) *UsageLogUpdate {
	return ulu.SetGroupID(g.ID)
}

// Mutation returns the UsageLogMutation object of the builder.
func (ulu *UsageLogUpdate) Mutation() *UsageLogMutation {
	return ulu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ulu *UsageLogUpdate) ClearUser() *UsageLogUpdate {
	ulu.mutation.ClearUser()
	return ulu
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (ulu *UsageLogUpdate) ClearAPIKey() *UsageLogUpdate {
	ulu.mutation.ClearAPIKey()
	return ulu
}

// ClearAccount clears the "account" edge to the Account entity.
func (ulu *UsageLogUpdate) ClearAccount() *UsageLogUpdate {
	ulu.mutation.ClearAccount()
	return ulu
}

// ClearGroup clears the "group" edge to the Group entity.
func (ulu *UsageLogUpdate) ClearGroup() *UsageLogUpdate {
	ulu.mutation.ClearGroup()
	return ulu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ulu *UsageLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ulu.sqlSave, ulu.mutation, ulu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ulu *UsageLogUpdate) SaveX(ctx context.Context) int {
	affected, err := ulu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ulu *UsageLogUpdate) Exec(ctx context.Context) error {
	_, err := ulu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ulu *UsageLogUpdate) ExecX(ctx context.Context) {
	if err := ulu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ulu *UsageLogUpdate) check() error {
	if v, ok := ulu.mutation.Platform(); ok {
		if err := usagelog.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UsageLog.platform": %w`, err)}
		}
	}
	if v, ok := ulu.mutation.Model(); ok {
		if err := usagelog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "UsageLog.model": %w`, err)}
		}
	}
	if _, ok := ulu.mutation.UserID(); ulu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UsageLog.user"`)
	}
	if _, ok := ulu.mutation.AccountID(); ulu.mutation.AccountCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UsageLog.account"`)
	}
	return nil
}

func (ulu *UsageLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ulu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagelog.Table, usagelog.Columns, sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt))
	if ps := ulu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ulu.mutation.Platform(); ok {
		_spec.SetField(usagelog.FieldPlatform, field.TypeString, value)
	}
	if value, ok := ulu.mutation.Model(); ok {
		_spec.SetField(usagelog.FieldModel, field.TypeString, value)
	}
	if value, ok := ulu.mutation.InputTokens(); ok {
		_spec.SetField(usagelog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := ulu.mutation.AddedInputTokens(); ok {
		_spec.AddField(usagelog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := ulu.mutation.OutputTokens(); ok {
		_spec.SetField(usagelog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := ulu.mutation.AddedOutputTokens(); ok {
		_spec.AddField(usagelog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := ulu.mutation.CachedInputTokens(); ok {
		_spec.SetField(usagelog.FieldCachedInputTokens, field.TypeInt, value)
	}
	if value, ok := ulu.mutation.AddedCachedInputTokens(); ok {
		_spec.AddField(usagelog.FieldCachedInputTokens, field.TypeInt, value)
	}
	if value, ok := ulu.mutation.CacheTokens(); ok {
		_spec.SetField(usagelog.FieldCacheTokens, field.TypeInt, value)
	}
	if value, ok := ulu.mutation.AddedCacheTokens(); ok {
		_spec.AddField(usagelog.FieldCacheTokens, field.TypeInt, value)
	}
	if value, ok := ulu.mutation.ReasoningOutputTokens(); ok {
		_spec.SetField(usagelog.FieldReasoningOutputTokens, field.TypeInt, value)
	}
	if value, ok := ulu.mutation.AddedReasoningOutputTokens(); ok {
		_spec.AddField(usagelog.FieldReasoningOutputTokens, field.TypeInt, value)
	}
	if value, ok := ulu.mutation.InputCost(); ok {
		_spec.SetField(usagelog.FieldInputCost, field.TypeFloat64, value)
	}
	if value, ok := ulu.mutation.AddedInputCost(); ok {
		_spec.AddField(usagelog.FieldInputCost, field.TypeFloat64, value)
	}
	if value, ok := ulu.mutation.OutputCost(); ok {
		_spec.SetField(usagelog.FieldOutputCost, field.TypeFloat64, value)
	}
	if value, ok := ulu.mutation.AddedOutputCost(); ok {
		_spec.AddField(usagelog.FieldOutputCost, field.TypeFloat64, value)
	}
	if value, ok := ulu.mutation.CachedInputCost(); ok {
		_spec.SetField(usagelog.FieldCachedInputCost, field.TypeFloat64, value)
	}
	if value, ok := ulu.mutation.AddedCachedInputCost(); ok {
		_spec.AddField(usagelog.FieldCachedInputCost, field.TypeFloat64, value)
	}
	if value, ok := ulu.mutation.CacheCost(); ok {
		_spec.SetField(usagelog.FieldCacheCost, field.TypeFloat64, value)
	}
	if value, ok := ulu.mutation.AddedCacheCost(); ok {
		_spec.AddField(usagelog.FieldCacheCost, field.TypeFloat64, value)
	}
	if value, ok := ulu.mutation.TotalCost(); ok {
		_spec.SetField(usagelog.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := ulu.mutation.AddedTotalCost(); ok {
		_spec.AddField(usagelog.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := ulu.mutation.ActualCost(); ok {
		_spec.SetField(usagelog.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := ulu.mutation.AddedActualCost(); ok {
		_spec.AddField(usagelog.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := ulu.mutation.RateMultiplier(); ok {
		_spec.SetField(usagelog.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := ulu.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(usagelog.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := ulu.mutation.AccountRateMultiplier(); ok {
		_spec.SetField(usagelog.FieldAccountRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := ulu.mutation.AddedAccountRateMultiplier(); ok {
		_spec.AddField(usagelog.FieldAccountRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := ulu.mutation.ServiceTier(); ok {
		_spec.SetField(usagelog.FieldServiceTier, field.TypeString, value)
	}
	if value, ok := ulu.mutation.Stream(); ok {
		_spec.SetField(usagelog.FieldStream, field.TypeBool, value)
	}
	if value, ok := ulu.mutation.DurationMs(); ok {
		_spec.SetField(usagelog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := ulu.mutation.AddedDurationMs(); ok {
		_spec.AddField(usagelog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := ulu.mutation.FirstTokenMs(); ok {
		_spec.SetField(usagelog.FieldFirstTokenMs, field.TypeInt64, value)
	}
	if value, ok := ulu.mutation.AddedFirstTokenMs(); ok {
		_spec.AddField(usagelog.FieldFirstTokenMs, field.TypeInt64, value)
	}
	if value, ok := ulu.mutation.UserAgent(); ok {
		_spec.SetField(usagelog.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := ulu.mutation.IPAddress(); ok {
		_spec.SetField(usagelog.FieldIPAddress, field.TypeString, value)
	}
	if ulu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.UserTable,
			Columns: []string{usagelog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ulu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.UserTable,
			Columns: []string{usagelog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ulu.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.APIKeyTable,
			Columns: []string{usagelog.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ulu.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.APIKeyTable,
			Columns: []string{usagelog.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ulu.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.AccountTable,
			Columns: []string{usagelog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ulu.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.AccountTable,
			Columns: []string{usagelog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ulu.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.GroupTable,
			Columns: []string{usagelog.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ulu.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.GroupTable,
			Columns: []string{usagelog.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ulu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ulu.mutation.done = true
	return n, nil
}

// UsageLogUpdateOne is the builder for updating a single UsageLog entity.
type UsageLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageLogMutation
}

// SetPlatform sets the "platform" field.
func (uluo *UsageLogUpdateOne) SetPlatform(s string) *UsageLogUpdateOne {
	uluo.mutation.SetPlatform(s)
	return uluo
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillablePlatform(s *string) *UsageLogUpdateOne {
	if s != nil {
		uluo.SetPlatform(*s)
	}
	return uluo
}

// SetModel sets the "model" field.
func (uluo *UsageLogUpdateOne) SetModel(s string) *UsageLogUpdateOne {
	uluo.mutation.SetModel(s)
	return uluo
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableModel(s *string) *UsageLogUpdateOne {
	if s != nil {
		uluo.SetModel(*s)
	}
	return uluo
}

// SetInputTokens sets the "input_tokens" field.
func (uluo *UsageLogUpdateOne) SetInputTokens(i int) *UsageLogUpdateOne {
	uluo.mutation.ResetInputTokens()
	uluo.mutation.SetInputTokens(i)
	return uluo
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableInputTokens(i *int) *UsageLogUpdateOne {
	if i != nil {
		uluo.SetInputTokens(*i)
	}
	return uluo
}

// AddInputTokens adds i to the "input_tokens" field.
func (uluo *UsageLogUpdateOne) AddInputTokens(i int) *UsageLogUpdateOne {
	uluo.mutation.AddInputTokens(i)
	return uluo
}

// SetOutputTokens sets the "output_tokens" field.
func (uluo *UsageLogUpdateOne) SetOutputTokens(i int) *UsageLogUpdateOne {
	uluo.mutation.ResetOutputTokens()
	uluo.mutation.SetOutputTokens(i)
	return uluo
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableOutputTokens(i *int) *UsageLogUpdateOne {
	if i != nil {
		uluo.SetOutputTokens(*i)
	}
	return uluo
}

// AddOutputTokens adds i to the "output_tokens" field.
func (uluo *UsageLogUpdateOne) AddOutputTokens(i int) *UsageLogUpdateOne {
	uluo.mutation.AddOutputTokens(i)
	return uluo
}

// SetCachedInputTokens sets the "cached_input_tokens" field.
func (uluo *UsageLogUpdateOne) SetCachedInputTokens(i int) *UsageLogUpdateOne {
	uluo.mutation.ResetCachedInputTokens()
	uluo.mutation.SetCachedInputTokens(i)
	return uluo
}

// SetNillableCachedInputTokens sets the "cached_input_tokens" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableCachedInputTokens(i *int) *UsageLogUpdateOne {
	if i != nil {
		uluo.SetCachedInputTokens(*i)
	}
	return uluo
}

// AddCachedInputTokens adds i to the "cached_input_tokens" field.
func (uluo *UsageLogUpdateOne) AddCachedInputTokens(i int) *UsageLogUpdateOne {
	uluo.mutation.AddCachedInputTokens(i)
	return uluo
}

// SetCacheTokens sets the "cache_tokens" field.
func (uluo *UsageLogUpdateOne) SetCacheTokens(i int) *UsageLogUpdateOne {
	uluo.mutation.ResetCacheTokens()
	uluo.mutation.SetCacheTokens(i)
	return uluo
}

// SetNillableCacheTokens sets the "cache_tokens" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableCacheTokens(i *int) *UsageLogUpdateOne {
	if i != nil {
		uluo.SetCacheTokens(*i)
	}
	return uluo
}

// AddCacheTokens adds i to the "cache_tokens" field.
func (uluo *UsageLogUpdateOne) AddCacheTokens(i int) *UsageLogUpdateOne {
	uluo.mutation.AddCacheTokens(i)
	return uluo
}

// SetReasoningOutputTokens sets the "reasoning_output_tokens" field.
func (uluo *UsageLogUpdateOne) SetReasoningOutputTokens(i int) *UsageLogUpdateOne {
	uluo.mutation.ResetReasoningOutputTokens()
	uluo.mutation.SetReasoningOutputTokens(i)
	return uluo
}

// SetNillableReasoningOutputTokens sets the "reasoning_output_tokens" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableReasoningOutputTokens(i *int) *UsageLogUpdateOne {
	if i != nil {
		uluo.SetReasoningOutputTokens(*i)
	}
	return uluo
}

// AddReasoningOutputTokens adds i to the "reasoning_output_tokens" field.
func (uluo *UsageLogUpdateOne) AddReasoningOutputTokens(i int) *UsageLogUpdateOne {
	uluo.mutation.AddReasoningOutputTokens(i)
	return uluo
}

// SetInputCost sets the "input_cost" field.
func (uluo *UsageLogUpdateOne) SetInputCost(f float64) *UsageLogUpdateOne {
	uluo.mutation.ResetInputCost()
	uluo.mutation.SetInputCost(f)
	return uluo
}

// SetNillableInputCost sets the "input_cost" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableInputCost(f *float64) *UsageLogUpdateOne {
	if f != nil {
		uluo.SetInputCost(*f)
	}
	return uluo
}

// AddInputCost adds f to the "input_cost" field.
func (uluo *UsageLogUpdateOne) AddInputCost(f float64) *UsageLogUpdateOne {
	uluo.mutation.AddInputCost(f)
	return uluo
}

// SetOutputCost sets the "output_cost" field.
func (uluo *UsageLogUpdateOne) SetOutputCost(f float64) *UsageLogUpdateOne {
	uluo.mutation.ResetOutputCost()
	uluo.mutation.SetOutputCost(f)
	return uluo
}

// SetNillableOutputCost sets the "output_cost" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableOutputCost(f *float64) *UsageLogUpdateOne {
	if f != nil {
		uluo.SetOutputCost(*f)
	}
	return uluo
}

// AddOutputCost adds f to the "output_cost" field.
func (uluo *UsageLogUpdateOne) AddOutputCost(f float64) *UsageLogUpdateOne {
	uluo.mutation.AddOutputCost(f)
	return uluo
}

// SetCachedInputCost sets the "cached_input_cost" field.
func (uluo *UsageLogUpdateOne) SetCachedInputCost(f float64) *UsageLogUpdateOne {
	uluo.mutation.ResetCachedInputCost()
	uluo.mutation.SetCachedInputCost(f)
	return uluo
}

// SetNillableCachedInputCost sets the "cached_input_cost" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableCachedInputCost(f *float64) *UsageLogUpdateOne {
	if f != nil {
		uluo.SetCachedInputCost(*f)
	}
	return uluo
}

// AddCachedInputCost adds f to the "cached_input_cost" field.
func (uluo *UsageLogUpdateOne) AddCachedInputCost(f float64) *UsageLogUpdateOne {
	uluo.mutation.AddCachedInputCost(f)
	return uluo
}

// SetCacheCost sets the "cache_cost" field.
func (uluo *UsageLogUpdateOne) SetCacheCost(f float64) *UsageLogUpdateOne {
	uluo.mutation.ResetCacheCost()
	uluo.mutation.SetCacheCost(f)
	return uluo
}

// SetNillableCacheCost sets the "cache_cost" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableCacheCost(f *float64) *UsageLogUpdateOne {
	if f != nil {
		uluo.SetCacheCost(*f)
	}
	return uluo
}

// AddCacheCost adds f to the "cache_cost" field.
func (uluo *UsageLogUpdateOne) AddCacheCost(f float64) *UsageLogUpdateOne {
	uluo.mutation.AddCacheCost(f)
	return uluo
}

// SetTotalCost sets the "total_cost" field.
func (uluo *UsageLogUpdateOne) SetTotalCost(f float64) *UsageLogUpdateOne {
	uluo.mutation.ResetTotalCost()
	uluo.mutation.SetTotalCost(f)
	return uluo
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableTotalCost(f *float64) *UsageLogUpdateOne {
	if f != nil {
		uluo.SetTotalCost(*f)
	}
	return uluo
}

// AddTotalCost adds f to the "total_cost" field.
func (uluo *UsageLogUpdateOne) AddTotalCost(f float64) *UsageLogUpdateOne {
	uluo.mutation.AddTotalCost(f)
	return uluo
}

// SetActualCost sets the "actual_cost" field.
func (uluo *UsageLogUpdateOne) SetActualCost(f float64) *UsageLogUpdateOne {
	uluo.mutation.ResetActualCost()
	uluo.mutation.SetActualCost(f)
	return uluo
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableActualCost(f *float64) *UsageLogUpdateOne {
	if f != nil {
		uluo.SetActualCost(*f)
	}
	return uluo
}

// AddActualCost adds f to the "actual_cost" field.
func (uluo *UsageLogUpdateOne) AddActualCost(f float64) *UsageLogUpdateOne {
	uluo.mutation.AddActualCost(f)
	return uluo
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (uluo *UsageLogUpdateOne) SetRateMultiplier(f float64) *UsageLogUpdateOne {
	uluo.mutation.ResetRateMultiplier()
	uluo.mutation.SetRateMultiplier(f)
	return uluo
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableRateMultiplier(f *float64) *UsageLogUpdateOne {
	if f != nil {
		uluo.SetRateMultiplier(*f)
	}
	return uluo
}

// AddRateMultiplier adds f to the "rate_multiplier" field.
func (uluo *UsageLogUpdateOne) AddRateMultiplier(f float64) *UsageLogUpdateOne {
	uluo.mutation.AddRateMultiplier(f)
	return uluo
}

// SetAccountRateMultiplier sets the "account_rate_multiplier" field.
func (uluo *UsageLogUpdateOne) SetAccountRateMultiplier(f float64) *UsageLogUpdateOne {
	uluo.mutation.ResetAccountRateMultiplier()
	uluo.mutation.SetAccountRateMultiplier(f)
	return uluo
}

// SetNillableAccountRateMultiplier sets the "account_rate_multiplier" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableAccountRateMultiplier(f *float64) *UsageLogUpdateOne {
	if f != nil {
		uluo.SetAccountRateMultiplier(*f)
	}
	return uluo
}

// AddAccountRateMultiplier adds f to the "account_rate_multiplier" field.
func (uluo *UsageLogUpdateOne) AddAccountRateMultiplier(f float64) *UsageLogUpdateOne {
	uluo.mutation.AddAccountRateMultiplier(f)
	return uluo
}

// SetServiceTier sets the "service_tier" field.
func (uluo *UsageLogUpdateOne) SetServiceTier(s string) *UsageLogUpdateOne {
	uluo.mutation.SetServiceTier(s)
	return uluo
}

// SetNillableServiceTier sets the "service_tier" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableServiceTier(s *string) *UsageLogUpdateOne {
	if s != nil {
		uluo.SetServiceTier(*s)
	}
	return uluo
}

// SetStream sets the "stream" field.
func (uluo *UsageLogUpdateOne) SetStream(b bool) *UsageLogUpdateOne {
	uluo.mutation.SetStream(b)
	return uluo
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableStream(b *bool) *UsageLogUpdateOne {
	if b != nil {
		uluo.SetStream(*b)
	}
	return uluo
}

// SetDurationMs sets the "duration_ms" field.
func (uluo *UsageLogUpdateOne) SetDurationMs(i int64) *UsageLogUpdateOne {
	uluo.mutation.ResetDurationMs()
	uluo.mutation.SetDurationMs(i)
	return uluo
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableDurationMs(i *int64) *UsageLogUpdateOne {
	if i != nil {
		uluo.SetDurationMs(*i)
	}
	return uluo
}

// AddDurationMs adds i to the "duration_ms" field.
func (uluo *UsageLogUpdateOne) AddDurationMs(i int64) *UsageLogUpdateOne {
	uluo.mutation.AddDurationMs(i)
	return uluo
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (uluo *UsageLogUpdateOne) SetFirstTokenMs(i int64) *UsageLogUpdateOne {
	uluo.mutation.ResetFirstTokenMs()
	uluo.mutation.SetFirstTokenMs(i)
	return uluo
}

// SetNillableFirstTokenMs sets the "first_token_ms" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableFirstTokenMs(i *int64) *UsageLogUpdateOne {
	if i != nil {
		uluo.SetFirstTokenMs(*i)
	}
	return uluo
}

// AddFirstTokenMs adds i to the "first_token_ms" field.
func (uluo *UsageLogUpdateOne) AddFirstTokenMs(i int64) *UsageLogUpdateOne {
	uluo.mutation.AddFirstTokenMs(i)
	return uluo
}

// SetUserAgent sets the "user_agent" field.
func (uluo *UsageLogUpdateOne) SetUserAgent(s string) *UsageLogUpdateOne {
	uluo.mutation.SetUserAgent(s)
	return uluo
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableUserAgent(s *string) *UsageLogUpdateOne {
	if s != nil {
		uluo.SetUserAgent(*s)
	}
	return uluo
}

// SetIPAddress sets the "ip_address" field.
func (uluo *UsageLogUpdateOne) SetIPAddress(s string) *UsageLogUpdateOne {
	uluo.mutation.SetIPAddress(s)
	return uluo
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableIPAddress(s *string) *UsageLogUpdateOne {
	if s != nil {
		uluo.SetIPAddress(*s)
	}
	return uluo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (uluo *UsageLogUpdateOne) SetUserID(id int) *UsageLogUpdateOne {
	uluo.mutation.SetUserID(id)
	return uluo
}

// SetUser sets the "user" edge to the User entity.
func (uluo *UsageLogUpdateOne) SetUser(u *User) *UsageLogUpdateOne {
	return uluo.SetUserID(u.ID)
}

// SetAPIKeyID sets the "api_key" edge to the APIKey entity by ID.
func (uluo *UsageLogUpdateOne) SetAPIKeyID(id int) *UsageLogUpdateOne {
	uluo.mutation.SetAPIKeyID(id)
	return uluo
}

// SetNillableAPIKeyID sets the "api_key" edge to the APIKey entity by ID if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableAPIKeyID(id *int) *UsageLogUpdateOne {
	if id != nil {
		uluo = uluo.SetAPIKeyID(*id)
	}
	return uluo
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (uluo *UsageLogUpdateOne) SetAPIKey(a *APIKey) *UsageLogUpdateOne {
	return uluo.SetAPIKeyID(a.ID)
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (uluo *UsageLogUpdateOne) SetAccountID(id int) *UsageLogUpdateOne {
	uluo.mutation.SetAccountID(id)
	return uluo
}

// SetAccount sets the "account" edge to the Account entity.
func (uluo *UsageLogUpdateOne) SetAccount(a *Account) *UsageLogUpdateOne {
	return uluo.SetAccountID(a.ID)
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (uluo *UsageLogUpdateOne) SetGroupID(id int) *UsageLogUpdateOne {
	uluo.mutation.SetGroupID(id)
	return uluo
}

// SetNillableGroupID sets the "group" edge to the Group entity by ID if the given value is not nil.
func (uluo *UsageLogUpdateOne) SetNillableGroupID(id *int) *UsageLogUpdateOne {
	if id != nil {
		uluo = uluo.SetGroupID(*id)
	}
	return uluo
}

// SetGroup sets the "group" edge to the Group entity.
func (uluo *UsageLogUpdateOne) SetGroup(g *Group) *UsageLogUpdateOne {
	return uluo.SetGroupID(g.ID)
}

// Mutation returns the UsageLogMutation object of the builder.
func (uluo *UsageLogUpdateOne) Mutation() *UsageLogMutation {
	return uluo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (uluo *UsageLogUpdateOne) ClearUser() *UsageLogUpdateOne {
	uluo.mutation.ClearUser()
	return uluo
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (uluo *UsageLogUpdateOne) ClearAPIKey() *UsageLogUpdateOne {
	uluo.mutation.ClearAPIKey()
	return uluo
}

// ClearAccount clears the "account" edge to the Account entity.
func (uluo *UsageLogUpdateOne) ClearAccount() *UsageLogUpdateOne {
	uluo.mutation.ClearAccount()
	return uluo
}

// ClearGroup clears the "group" edge to the Group entity.
func (uluo *UsageLogUpdateOne) ClearGroup() *UsageLogUpdateOne {
	uluo.mutation.ClearGroup()
	return uluo
}

// Where appends a list predicates to the UsageLogUpdate builder.
func (uluo *UsageLogUpdateOne) Where(ps ...predicate.UsageLog) *UsageLogUpdateOne {
	uluo.mutation.Where(ps...)
	return uluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uluo *UsageLogUpdateOne) Select(field string, fields ...string) *UsageLogUpdateOne {
	uluo.fields = append([]string{field}, fields...)
	return uluo
}

// Save executes the query and returns the updated UsageLog entity.
func (uluo *UsageLogUpdateOne) Save(ctx context.Context) (*UsageLog, error) {
	return withHooks(ctx, uluo.sqlSave, uluo.mutation, uluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uluo *UsageLogUpdateOne) SaveX(ctx context.Context) *UsageLog {
	node, err := uluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uluo *UsageLogUpdateOne) Exec(ctx context.Context) error {
	_, err := uluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uluo *UsageLogUpdateOne) ExecX(ctx context.Context) {
	if err := uluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uluo *UsageLogUpdateOne) check() error {
	if v, ok := uluo.mutation.Platform(); ok {
		if err := usagelog.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UsageLog.platform": %w`, err)}
		}
	}
	if v, ok := uluo.mutation.Model(); ok {
		if err := usagelog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "UsageLog.model": %w`, err)}
		}
	}
	if _, ok := uluo.mutation.UserID(); uluo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UsageLog.user"`)
	}
	if _, ok := uluo.mutation.AccountID(); uluo.mutation.AccountCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UsageLog.account"`)
	}
	return nil
}

func (uluo *UsageLogUpdateOne) sqlSave(ctx context.Context) (_node *UsageLog, err error) {
	if err := uluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagelog.Table, usagelog.Columns, sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt))
	id, ok := uluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagelog.FieldID)
		for _, f := range fields {
			if !usagelog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uluo.mutation.Platform(); ok {
		_spec.SetField(usagelog.FieldPlatform, field.TypeString, value)
	}
	if value, ok := uluo.mutation.Model(); ok {
		_spec.SetField(usagelog.FieldModel, field.TypeString, value)
	}
	if value, ok := uluo.mutation.InputTokens(); ok {
		_spec.SetField(usagelog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := uluo.mutation.AddedInputTokens(); ok {
		_spec.AddField(usagelog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := uluo.mutation.OutputTokens(); ok {
		_spec.SetField(usagelog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := uluo.mutation.AddedOutputTokens(); ok {
		_spec.AddField(usagelog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := uluo.mutation.CachedInputTokens(); ok {
		_spec.SetField(usagelog.FieldCachedInputTokens, field.TypeInt, value)
	}
	if value, ok := uluo.mutation.AddedCachedInputTokens(); ok {
		_spec.AddField(usagelog.FieldCachedInputTokens, field.TypeInt, value)
	}
	if value, ok := uluo.mutation.CacheTokens(); ok {
		_spec.SetField(usagelog.FieldCacheTokens, field.TypeInt, value)
	}
	if value, ok := uluo.mutation.AddedCacheTokens(); ok {
		_spec.AddField(usagelog.FieldCacheTokens, field.TypeInt, value)
	}
	if value, ok := uluo.mutation.ReasoningOutputTokens(); ok {
		_spec.SetField(usagelog.FieldReasoningOutputTokens, field.TypeInt, value)
	}
	if value, ok := uluo.mutation.AddedReasoningOutputTokens(); ok {
		_spec.AddField(usagelog.FieldReasoningOutputTokens, field.TypeInt, value)
	}
	if value, ok := uluo.mutation.InputCost(); ok {
		_spec.SetField(usagelog.FieldInputCost, field.TypeFloat64, value)
	}
	if value, ok := uluo.mutation.AddedInputCost(); ok {
		_spec.AddField(usagelog.FieldInputCost, field.TypeFloat64, value)
	}
	if value, ok := uluo.mutation.OutputCost(); ok {
		_spec.SetField(usagelog.FieldOutputCost, field.TypeFloat64, value)
	}
	if value, ok := uluo.mutation.AddedOutputCost(); ok {
		_spec.AddField(usagelog.FieldOutputCost, field.TypeFloat64, value)
	}
	if value, ok := uluo.mutation.CachedInputCost(); ok {
		_spec.SetField(usagelog.FieldCachedInputCost, field.TypeFloat64, value)
	}
	if value, ok := uluo.mutation.AddedCachedInputCost(); ok {
		_spec.AddField(usagelog.FieldCachedInputCost, field.TypeFloat64, value)
	}
	if value, ok := uluo.mutation.CacheCost(); ok {
		_spec.SetField(usagelog.FieldCacheCost, field.TypeFloat64, value)
	}
	if value, ok := uluo.mutation.AddedCacheCost(); ok {
		_spec.AddField(usagelog.FieldCacheCost, field.TypeFloat64, value)
	}
	if value, ok := uluo.mutation.TotalCost(); ok {
		_spec.SetField(usagelog.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := uluo.mutation.AddedTotalCost(); ok {
		_spec.AddField(usagelog.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := uluo.mutation.ActualCost(); ok {
		_spec.SetField(usagelog.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := uluo.mutation.AddedActualCost(); ok {
		_spec.AddField(usagelog.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := uluo.mutation.RateMultiplier(); ok {
		_spec.SetField(usagelog.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := uluo.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(usagelog.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := uluo.mutation.AccountRateMultiplier(); ok {
		_spec.SetField(usagelog.FieldAccountRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := uluo.mutation.AddedAccountRateMultiplier(); ok {
		_spec.AddField(usagelog.FieldAccountRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := uluo.mutation.ServiceTier(); ok {
		_spec.SetField(usagelog.FieldServiceTier, field.TypeString, value)
	}
	if value, ok := uluo.mutation.Stream(); ok {
		_spec.SetField(usagelog.FieldStream, field.TypeBool, value)
	}
	if value, ok := uluo.mutation.DurationMs(); ok {
		_spec.SetField(usagelog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := uluo.mutation.AddedDurationMs(); ok {
		_spec.AddField(usagelog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := uluo.mutation.FirstTokenMs(); ok {
		_spec.SetField(usagelog.FieldFirstTokenMs, field.TypeInt64, value)
	}
	if value, ok := uluo.mutation.AddedFirstTokenMs(); ok {
		_spec.AddField(usagelog.FieldFirstTokenMs, field.TypeInt64, value)
	}
	if value, ok := uluo.mutation.UserAgent(); ok {
		_spec.SetField(usagelog.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := uluo.mutation.IPAddress(); ok {
		_spec.SetField(usagelog.FieldIPAddress, field.TypeString, value)
	}
	if uluo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.UserTable,
			Columns: []string{usagelog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uluo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.UserTable,
			Columns: []string{usagelog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uluo.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.APIKeyTable,
			Columns: []string{usagelog.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uluo.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.APIKeyTable,
			Columns: []string{usagelog.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uluo.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.AccountTable,
			Columns: []string{usagelog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uluo.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.AccountTable,
			Columns: []string{usagelog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uluo.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.GroupTable,
			Columns: []string{usagelog.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uluo.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.GroupTable,
			Columns: []string{usagelog.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UsageLog{config: uluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uluo.mutation.done = true
	return _node, nil
}
