// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/account"
	"github.com/DouDOU-start/airgate-core/ent/apikey"
	"github.com/DouDOU-start/airgate-core/ent/group"
	"github.com/DouDOU-start/airgate-core/ent/usagelog"
	"github.com/DouDOU-start/airgate-core/ent/user"
)

// UsageLog is the model entity for the UsageLog schema.
type UsageLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int `json:"output_tokens,omitempty"`
	// CachedInputTokens holds the value of the "cached_input_tokens" field.
	CachedInputTokens int `json:"cached_input_tokens,omitempty"`
	// CacheTokens holds the value of the "cache_tokens" field.
	CacheTokens int `json:"cache_tokens,omitempty"`
	// ReasoningOutputTokens holds the value of the "reasoning_output_tokens" field.
	ReasoningOutputTokens int `json:"reasoning_output_tokens,omitempty"`
	// InputCost holds the value of the "input_cost" field.
	InputCost float64 `json:"input_cost,omitempty"`
	// OutputCost holds the value of the "output_cost" field.
	OutputCost float64 `json:"output_cost,omitempty"`
	// CachedInputCost holds the value of the "cached_input_cost" field.
	CachedInputCost float64 `json:"cached_input_cost,omitempty"`
	// CacheCost holds the value of the "cache_cost" field.
	CacheCost float64 `json:"cache_cost,omitempty"`
	// TotalCost holds the value of the "total_cost" field.
	TotalCost float64 `json:"total_cost,omitempty"`
	// ActualCost holds the value of the "actual_cost" field.
	ActualCost float64 `json:"actual_cost,omitempty"`
	// RateMultiplier holds the value of the "rate_multiplier" field.
	RateMultiplier float64 `json:"rate_multiplier,omitempty"`
	// AccountRateMultiplier holds the value of the "account_rate_multiplier" field.
	AccountRateMultiplier float64 `json:"account_rate_multiplier,omitempty"`
	// ServiceTier holds the value of the "service_tier" field.
	ServiceTier string `json:"service_tier,omitempty"`
	// Stream holds the value of the "stream" field.
	Stream bool `json:"stream,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs int64 `json:"duration_ms,omitempty"`
	// FirstTokenMs holds the value of the "first_token_ms" field.
	FirstTokenMs int64 `json:"first_token_ms,omitempty"`
	// UserAgent holds the value of the "user_agent" field.
	UserAgent string `json:"user_agent,omitempty"`
	// IPAddress holds the value of the "ip_address" field.
	IPAddress string `json:"ip_address,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsageLogQuery when eager-loading is set.
	Edges              UsageLogEdges `json:"edges"`
	api_key_usage_logs *int
	account_usage_logs *int
	group_usage_logs   *int
	user_usage_logs    *int
	selectValues       sql.SelectValues
}

// UsageLogEdges holds the relations/edges for other nodes in the graph.
type UsageLogEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagelog.FieldStream:
			values[i] = new(sql.NullBool)
		case usagelog.FieldInputCost, usagelog.FieldOutputCost, usagelog.FieldCachedInputCost, usagelog.FieldCacheCost, usagelog.FieldTotalCost, usagelog.FieldActualCost, usagelog.FieldRateMultiplier, usagelog.FieldAccountRateMultiplier:
			values[i] = new(sql.NullFloat64)
		case usagelog.FieldID, usagelog.FieldInputTokens, usagelog.FieldOutputTokens, usagelog.FieldCachedInputTokens, usagelog.FieldCacheTokens, usagelog.FieldReasoningOutputTokens, usagelog.FieldDurationMs, usagelog.FieldFirstTokenMs:
			values[i] = new(sql.NullInt64)
		case usagelog.FieldPlatform, usagelog.FieldModel, usagelog.FieldServiceTier, usagelog.FieldUserAgent, usagelog.FieldIPAddress:
			values[i] = new(sql.NullString)
		case usagelog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case usagelog.ForeignKeys[0]: // api_key_usage_logs
			values[i] = new(sql.NullInt64)
		case usagelog.ForeignKeys[1]: // account_usage_logs
			values[i] = new(sql.NullInt64)
		case usagelog.ForeignKeys[2]: // group_usage_logs
			values[i] = new(sql.NullInt64)
		case usagelog.ForeignKeys[3]: // user_usage_logs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageLog fields.
func (ul *UsageLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagelog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ul.ID = int(value.Int64)
		case usagelog.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				ul.Platform = value.String
			}
		case usagelog.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				ul.Model = value.String
			}
		case usagelog.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				ul.InputTokens = int(value.Int64)
			}
		case usagelog.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				ul.OutputTokens = int(value.Int64)
			}
		case usagelog.FieldCachedInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cached_input_tokens", values[i])
			} else if value.Valid {
				ul.CachedInputTokens = int(value.Int64)
			}
		case usagelog.FieldCacheTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_tokens", values[i])
			} else if value.Valid {
				ul.CacheTokens = int(value.Int64)
			}
		case usagelog.FieldReasoningOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reasoning_output_tokens", values[i])
			} else if value.Valid {
				ul.ReasoningOutputTokens = int(value.Int64)
			}
		case usagelog.FieldInputCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field input_cost", values[i])
			} else if value.Valid {
				ul.InputCost = value.Float64
			}
		case usagelog.FieldOutputCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field output_cost", values[i])
			} else if value.Valid {
				ul.OutputCost = value.Float64
			}
		case usagelog.FieldCachedInputCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cached_input_cost", values[i])
			} else if value.Valid {
				ul.CachedInputCost = value.Float64
			}
		case usagelog.FieldCacheCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_cost", values[i])
			} else if value.Valid {
				ul.CacheCost = value.Float64
			}
		case usagelog.FieldTotalCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_cost", values[i])
			} else if value.Valid {
				ul.TotalCost = value.Float64
			}
		case usagelog.FieldActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cost", values[i])
			} else if value.Valid {
				ul.ActualCost = value.Float64
			}
		case usagelog.FieldRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_multiplier", values[i])
			} else if value.Valid {
				ul.RateMultiplier = value.Float64
			}
		case usagelog.FieldAccountRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field account_rate_multiplier", values[i])
			} else if value.Valid {
				ul.AccountRateMultiplier = value.Float64
			}
		case usagelog.FieldServiceTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service_tier", values[i])
			} else if value.Valid {
				ul.ServiceTier = value.String
			}
		case usagelog.FieldStream:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field stream", values[i])
			} else if value.Valid {
				ul.Stream = value.Bool
			}
		case usagelog.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				ul.DurationMs = value.Int64
			}
		case usagelog.FieldFirstTokenMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field first_token_ms", values[i])
			} else if value.Valid {
				ul.FirstTokenMs = value.Int64
			}
		case usagelog.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				ul.UserAgent = value.String
			}
		case usagelog.FieldIPAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_address", values[i])
			} else if value.Valid {
				ul.IPAddress = value.String
			}
		case usagelog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ul.CreatedAt = value.Time
			}
		case usagelog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field api_key_usage_logs", value)
			} else if value.Valid {
				ul.api_key_usage_logs = new(int)
				*ul.api_key_usage_logs = int(value.Int64)
			}
		case usagelog.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field account_usage_logs", value)
			} else if value.Valid {
				ul.account_usage_logs = new(int)
				*ul.account_usage_logs = int(value.Int64)
			}
		case usagelog.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field group_usage_logs", value)
			} else if value.Valid {
				ul.group_usage_logs = new(int)
				*ul.group_usage_logs = int(value.Int64)
			}
		case usagelog.ForeignKeys[3]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_usage_logs", value)
			} else if value.Valid {
				ul.user_usage_logs = new(int)
				*ul.user_usage_logs = int(value.Int64)
			}
		default:
			ul.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageLog.
// This includes values selected through modifiers, order, etc.
func (ul *UsageLog) Value(name string) (ent.Value, error) {
	return ul.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UsageLog entity.
func (ul *UsageLog) QueryUser() *UserQuery {
	return NewUsageLogClient(ul.config).QueryUser(ul)
}

// QueryAPIKey queries the "api_key" edge of the UsageLog entity.
func (ul *UsageLog) QueryAPIKey() *APIKeyQuery {
	return NewUsageLogClient(ul.config).QueryAPIKey(ul)
}

// QueryAccount queries the "account" edge of the UsageLog entity.
func (ul *UsageLog) QueryAccount() *AccountQuery {
	return NewUsageLogClient(ul.config).QueryAccount(ul)
}

// QueryGroup queries the "group" edge of the UsageLog entity.
func (ul *UsageLog) QueryGroup() *GroupQuery {
	return NewUsageLogClient(ul.config).QueryGroup(ul)
}

// Update returns a builder for updating this UsageLog.
// Note that you need to call UsageLog.Unwrap() before calling this method if this UsageLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (ul *UsageLog) Update() *UsageLogUpdateOne {
	return NewUsageLogClient(ul.config).UpdateOne(ul)
}

// Unwrap unwraps the UsageLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ul *UsageLog) Unwrap() *UsageLog {
	_tx, ok := ul.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageLog is not a transactional entity")
	}
	ul.config.driver = _tx.drv
	return ul
}

// String implements the fmt.Stringer.
func (ul *UsageLog) String() string {
	var builder strings.Builder
	builder.WriteString("UsageLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ul.ID))
	builder.WriteString("platform=")
	builder.WriteString(ul.Platform)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(ul.Model)
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", ul.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", ul.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("cached_input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", ul.CachedInputTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_tokens=")
	builder.WriteString(fmt.Sprintf("%v", ul.CacheTokens))
	builder.WriteString(", ")
	builder.WriteString("reasoning_output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", ul.ReasoningOutputTokens))
	builder.WriteString(", ")
	builder.WriteString("input_cost=")
	builder.WriteString(fmt.Sprintf("%v", ul.InputCost))
	builder.WriteString(", ")
	builder.WriteString("output_cost=")
	builder.WriteString(fmt.Sprintf("%v", ul.OutputCost))
	builder.WriteString(", ")
	builder.WriteString("cached_input_cost=")
	builder.WriteString(fmt.Sprintf("%v", ul.CachedInputCost))
	builder.WriteString(", ")
	builder.WriteString("cache_cost=")
	builder.WriteString(fmt.Sprintf("%v", ul.CacheCost))
	builder.WriteString(", ")
	builder.WriteString("total_cost=")
	builder.WriteString(fmt.Sprintf("%v", ul.TotalCost))
	builder.WriteString(", ")
	builder.WriteString("actual_cost=")
	builder.WriteString(fmt.Sprintf("%v", ul.ActualCost))
	builder.WriteString(", ")
	builder.WriteString("rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", ul.RateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("account_rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", ul.AccountRateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("service_tier=")
	builder.WriteString(ul.ServiceTier)
	builder.WriteString(", ")
	builder.WriteString("stream=")
	builder.WriteString(fmt.Sprintf("%v", ul.Stream))
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", ul.DurationMs))
	builder.WriteString(", ")
	builder.WriteString("first_token_ms=")
	builder.WriteString(fmt.Sprintf("%v", ul.FirstTokenMs))
	builder.WriteString(", ")
	builder.WriteString("user_agent=")
	builder.WriteString(ul.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("ip_address=")
	builder.WriteString(ul.IPAddress)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ul.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UsageLogs is a parsable slice of UsageLog.
type UsageLogs []*UsageLog
