// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"-"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Balance holds the value of the "balance" field.
	Balance float64 `json:"balance,omitempty"`
	// Role holds the value of the "role" field.
	Role user.Role `json:"role,omitempty"`
	// MaxConcurrency holds the value of the "max_concurrency" field.
	MaxConcurrency int `json:"max_concurrency,omitempty"`
	// TotpSecret holds the value of the "totp_secret" field.
	TotpSecret *string `json:"-"`
	// GroupRates holds the value of the "group_rates" field.
	GroupRates map[int64]float64 `json:"group_rates,omitempty"`
	// BalanceAlertThreshold holds the value of the "balance_alert_threshold" field.
	BalanceAlertThreshold float64 `json:"balance_alert_threshold,omitempty"`
	// BalanceAlertNotified holds the value of the "balance_alert_notified" field.
	BalanceAlertNotified bool `json:"balance_alert_notified,omitempty"`
	// Status holds the value of the "status" field.
	Status user.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// APIKeys holds the value of the api_keys edge.
	APIKeys []*APIKey `json:"api_keys,omitempty"`
	// Subscriptions holds the value of the subscriptions edge.
	Subscriptions []*UserSubscription `json:"subscriptions,omitempty"`
	// UsageLogs holds the value of the usage_logs edge.
	UsageLogs []*UsageLog `json:"usage_logs,omitempty"`
	// AllowedGroups holds the value of the allowed_groups edge.
	AllowedGroups []*Group `json:"allowed_groups,omitempty"`
	// BalanceLogs holds the value of the balance_logs edge.
	BalanceLogs []*BalanceLog `json:"balance_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// APIKeysOrErr returns the APIKeys value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) APIKeysOrErr() ([]*APIKey, error) {
	if e.loadedTypes[0] {
		return e.APIKeys, nil
	}
	return nil, &NotLoadedError{edge: "api_keys"}
}

// SubscriptionsOrErr returns the Subscriptions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SubscriptionsOrErr() ([]*UserSubscription, error) {
	if e.loadedTypes[1] {
		return e.Subscriptions, nil
	}
	return nil, &NotLoadedError{edge: "subscriptions"}
}

// UsageLogsOrErr returns the UsageLogs value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) UsageLogsOrErr() ([]*UsageLog, error) {
	if e.loadedTypes[2] {
		return e.UsageLogs, nil
	}
	return nil, &NotLoadedError{edge: "usage_logs"}
}

// AllowedGroupsOrErr returns the AllowedGroups value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AllowedGroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[3] {
		return e.AllowedGroups, nil
	}
	return nil, &NotLoadedError{edge: "allowed_groups"}
}

// BalanceLogsOrErr returns the BalanceLogs value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) BalanceLogsOrErr() ([]*BalanceLog, error) {
	if e.loadedTypes[4] {
		return e.BalanceLogs, nil
	}
	return nil, &NotLoadedError{edge: "balance_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldGroupRates:
			values[i] = new([]byte)
		case user.FieldBalanceAlertNotified:
			values[i] = new(sql.NullBool)
		case user.FieldBalance, user.FieldBalanceAlertThreshold:
			values[i] = new(sql.NullFloat64)
		case user.FieldID, user.FieldMaxConcurrency:
			values[i] = new(sql.NullInt64)
		case user.FieldEmail, user.FieldPasswordHash, user.FieldUsername, user.FieldRole, user.FieldTotpSecret, user.FieldStatus:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (u *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			u.ID = int(value.Int64)
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				u.Email = value.String
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				u.PasswordHash = value.String
			}
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				u.Username = value.String
			}
		case user.FieldBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value.Valid {
				u.Balance = value.Float64
			}
		case user.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				u.Role = user.Role(value.String)
			}
		case user.FieldMaxConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_concurrency", values[i])
			} else if value.Valid {
				u.MaxConcurrency = int(value.Int64)
			}
		case user.FieldTotpSecret:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field totp_secret", values[i])
			} else if value.Valid {
				u.TotpSecret = new(string)
				*u.TotpSecret = value.String
			}
		case user.FieldGroupRates:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field group_rates", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &u.GroupRates); err != nil {
					return fmt.Errorf("unmarshal field group_rates: %w", err)
				}
			}
		case user.FieldBalanceAlertThreshold:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_alert_threshold", values[i])
			} else if value.Valid {
				u.BalanceAlertThreshold = value.Float64
			}
		case user.FieldBalanceAlertNotified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field balance_alert_notified", values[i])
			} else if value.Valid {
				u.BalanceAlertNotified = value.Bool
			}
		case user.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				u.Status = user.Status(value.String)
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				u.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				u.UpdatedAt = value.Time
			}
		default:
			u.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (u *User) Value(name string) (ent.Value, error) {
	return u.selectValues.Get(name)
}

// QueryAPIKeys queries the "api_keys" edge of the User entity.
func (u *User) QueryAPIKeys() *APIKeyQuery {
	return NewUserClient(u.config).QueryAPIKeys(u)
}

// QuerySubscriptions queries the "subscriptions" edge of the User entity.
func (u *User) QuerySubscriptions() *UserSubscriptionQuery {
	return NewUserClient(u.config).QuerySubscriptions(u)
}

// QueryUsageLogs queries the "usage_logs" edge of the User entity.
func (u *User) QueryUsageLogs() *UsageLogQuery {
	return NewUserClient(u.config).QueryUsageLogs(u)
}

// QueryAllowedGroups queries the "allowed_groups" edge of the User entity.
func (u *User) QueryAllowedGroups() *GroupQuery {
	return NewUserClient(u.config).QueryAllowedGroups(u)
}

// QueryBalanceLogs queries the "balance_logs" edge of the User entity.
func (u *User) QueryBalanceLogs() *BalanceLogQuery {
	return NewUserClient(u.config).QueryBalanceLogs(u)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *User) Update() *UserUpdateOne {
	return NewUserClient(u.config).UpdateOne(u)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (u *User) Unwrap() *User {
	_tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	u.config.driver = _tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", u.ID))
	builder.WriteString("email=")
	builder.WriteString(u.Email)
	builder.WriteString(", ")
	builder.WriteString("password_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(u.Username)
	builder.WriteString(", ")
	builder.WriteString("balance=")
	builder.WriteString(fmt.Sprintf("%v", u.Balance))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", u.Role))
	builder.WriteString(", ")
	builder.WriteString("max_concurrency=")
	builder.WriteString(fmt.Sprintf("%v", u.MaxConcurrency))
	builder.WriteString(", ")
	builder.WriteString("totp_secret=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("group_rates=")
	builder.WriteString(fmt.Sprintf("%v", u.GroupRates))
	builder.WriteString(", ")
	builder.WriteString("balance_alert_threshold=")
	builder.WriteString(fmt.Sprintf("%v", u.BalanceAlertThreshold))
	builder.WriteString(", ")
	builder.WriteString("balance_alert_notified=")
	builder.WriteString(fmt.Sprintf("%v", u.BalanceAlertNotified))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", u.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(u.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(u.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
