// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "key_hash", Type: field.TypeString},
		{Name: "key_encrypted", Type: field.TypeString, Nullable: true},
		{Name: "ip_whitelist", Type: field.TypeJSON, Nullable: true},
		{Name: "ip_blacklist", Type: field.TypeJSON, Nullable: true},
		{Name: "quota_usd", Type: field.TypeFloat64, Default: 0},
		{Name: "used_quota", Type: field.TypeFloat64, Default: 0},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "group_api_keys", Type: field.TypeInt, Nullable: true},
		{Name: "user_api_keys", Type: field.TypeInt},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_keys_groups_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[12]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "api_keys_users_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[13]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "platform", Type: field.TypeString},
		{Name: "type", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "credentials", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "error", "disabled"}, Default: "active"},
		{Name: "priority", Type: field.TypeInt, Default: 50},
		{Name: "max_concurrency", Type: field.TypeInt, Default: 5},
		{Name: "rate_multiplier", Type: field.TypeFloat64, Default: 1},
		{Name: "error_msg", Type: field.TypeString, Default: ""},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "extra", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "account_proxy", Type: field.TypeInt, Nullable: true},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "accounts_proxies_proxy",
				Columns:    []*schema.Column{AccountsColumns[14]},
				RefColumns: []*schema.Column{ProxiesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// BalanceLogsColumns holds the columns for the "balance_logs" table.
	BalanceLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "action", Type: field.TypeEnum, Enums: []string{"add", "subtract", "set"}},
		{Name: "amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "before_balance", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "after_balance", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "remark", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_balance_logs", Type: field.TypeInt},
	}
	// BalanceLogsTable holds the schema information for the "balance_logs" table.
	BalanceLogsTable = &schema.Table{
		Name:       "balance_logs",
		Columns:    BalanceLogsColumns,
		PrimaryKey: []*schema.Column{BalanceLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "balance_logs_users_balance_logs",
				Columns:    []*schema.Column{BalanceLogsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "platform", Type: field.TypeString},
		{Name: "rate_multiplier", Type: field.TypeFloat64, Default: 1},
		{Name: "is_exclusive", Type: field.TypeBool, Default: false},
		{Name: "subscription_type", Type: field.TypeEnum, Enums: []string{"standard", "subscription"}, Default: "standard"},
		{Name: "quotas", Type: field.TypeJSON, Nullable: true},
		{Name: "model_routing", Type: field.TypeJSON, Nullable: true},
		{Name: "service_tier", Type: field.TypeString, Default: ""},
		{Name: "sort_weight", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
	}
	// OrdersColumns holds the columns for the "orders" table.
	OrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "order_no", Type: field.TypeString, Unique: true},
		{Name: "amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "paid", "failed", "expired"}, Default: "pending"},
		{Name: "channel", Type: field.TypeString, Default: ""},
		{Name: "paid_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_orders", Type: field.TypeInt},
	}
	// OrdersTable holds the schema information for the "orders" table.
	OrdersTable = &schema.Table{
		Name:       "orders",
		Columns:    OrdersColumns,
		PrimaryKey: []*schema.Column{OrdersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "orders_users_orders",
				Columns:    []*schema.Column{OrdersColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PluginsColumns holds the columns for the "plugins" table.
	PluginsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "platform", Type: field.TypeString, Default: ""},
		{Name: "version", Type: field.TypeString, Default: ""},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"gateway", "payment", "extension"}, Default: "gateway"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"installed", "enabled", "disabled"}, Default: "installed"},
		{Name: "config", Type: field.TypeJSON, Nullable: true},
		{Name: "binary_path", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PluginsTable holds the schema information for the "plugins" table.
	PluginsTable = &schema.Table{
		Name:       "plugins",
		Columns:    PluginsColumns,
		PrimaryKey: []*schema.Column{PluginsColumns[0]},
	}
	// PluginSourcesColumns holds the columns for the "plugin_sources" table.
	PluginSourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "url", Type: field.TypeString},
		{Name: "is_official", Type: field.TypeBool, Default: false},
		{Name: "last_sync_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PluginSourcesTable holds the schema information for the "plugin_sources" table.
	PluginSourcesTable = &schema.Table{
		Name:       "plugin_sources",
		Columns:    PluginSourcesColumns,
		PrimaryKey: []*schema.Column{PluginSourcesColumns[0]},
	}
	// ProxiesColumns holds the columns for the "proxies" table.
	ProxiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "protocol", Type: field.TypeEnum, Enums: []string{"http", "socks5"}, Default: "http"},
		{Name: "address", Type: field.TypeString},
		{Name: "port", Type: field.TypeInt},
		{Name: "username", Type: field.TypeString, Default: ""},
		{Name: "password", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProxiesTable holds the schema information for the "proxies" table.
	ProxiesTable = &schema.Table{
		Name:       "proxies",
		Columns:    ProxiesColumns,
		PrimaryKey: []*schema.Column{ProxiesColumns[0]},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, Default: ""},
		{Name: "group", Type: field.TypeString, Default: "general"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
	}
	// UsageLogsColumns holds the columns for the "usage_logs" table.
	UsageLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "platform", Type: field.TypeString},
		{Name: "model", Type: field.TypeString},
		{Name: "input_tokens", Type: field.TypeInt, Default: 0},
		{Name: "output_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cached_input_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_tokens", Type: field.TypeInt, Default: 0},
		{Name: "reasoning_output_tokens", Type: field.TypeInt, Default: 0},
		{Name: "input_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "output_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "cached_input_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "cache_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "total_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "actual_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "rate_multiplier", Type: field.TypeFloat64, Default: 1},
		{Name: "account_rate_multiplier", Type: field.TypeFloat64, Default: 1},
		{Name: "service_tier", Type: field.TypeString, Default: ""},
		{Name: "stream", Type: field.TypeBool, Default: false},
		{Name: "duration_ms", Type: field.TypeInt64, Default: 0},
		{Name: "first_token_ms", Type: field.TypeInt64, Default: 0},
		{Name: "user_agent", Type: field.TypeString, Default: ""},
		{Name: "ip_address", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "api_key_usage_logs", Type: field.TypeInt, Nullable: true},
		{Name: "account_usage_logs", Type: field.TypeInt},
		{Name: "group_usage_logs", Type: field.TypeInt, Nullable: true},
		{Name: "user_usage_logs", Type: field.TypeInt},
	}
	// UsageLogsTable holds the schema information for the "usage_logs" table.
	UsageLogsTable = &schema.Table{
		Name:       "usage_logs",
		Columns:    UsageLogsColumns,
		PrimaryKey: []*schema.Column{UsageLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "usage_logs_api_keys_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[23]},
				RefColumns: []*schema.Column{APIKeysColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "usage_logs_accounts_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[24]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "usage_logs_groups_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[25]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "usage_logs_users_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[26]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Default: ""},
		{Name: "balance", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "user"}, Default: "user"},
		{Name: "max_concurrency", Type: field.TypeInt, Default: 5},
		{Name: "totp_secret", Type: field.TypeString, Nullable: true},
		{Name: "group_rates", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserSubscriptionsColumns holds the columns for the "user_subscriptions" table.
	UserSubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "effective_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "usage", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "expired", "suspended"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "group_subscriptions", Type: field.TypeInt},
		{Name: "user_subscriptions", Type: field.TypeInt},
	}
	// UserSubscriptionsTable holds the schema information for the "user_subscriptions" table.
	UserSubscriptionsTable = &schema.Table{
		Name:       "user_subscriptions",
		Columns:    UserSubscriptionsColumns,
		PrimaryKey: []*schema.Column{UserSubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_subscriptions_groups_subscriptions",
				Columns:    []*schema.Column{UserSubscriptionsColumns[7]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_subscriptions_users_subscriptions",
				Columns:    []*schema.Column{UserSubscriptionsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// AccountGroupsColumns holds the columns for the "account_groups" table.
	AccountGroupsColumns = []*schema.Column{
		{Name: "account_id", Type: field.TypeInt},
		{Name: "group_id", Type: field.TypeInt},
	}
	// AccountGroupsTable holds the schema information for the "account_groups" table.
	AccountGroupsTable = &schema.Table{
		Name:       "account_groups",
		Columns:    AccountGroupsColumns,
		PrimaryKey: []*schema.Column{AccountGroupsColumns[0], AccountGroupsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "account_groups_account_id",
				Columns:    []*schema.Column{AccountGroupsColumns[0]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "account_groups_group_id",
				Columns:    []*schema.Column{AccountGroupsColumns[1]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserAllowedGroupsColumns holds the columns for the "user_allowed_groups" table.
	UserAllowedGroupsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "group_id", Type: field.TypeInt},
	}
	// UserAllowedGroupsTable holds the schema information for the "user_allowed_groups" table.
	UserAllowedGroupsTable = &schema.Table{
		Name:       "user_allowed_groups",
		Columns:    UserAllowedGroupsColumns,
		PrimaryKey: []*schema.Column{UserAllowedGroupsColumns[0], UserAllowedGroupsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_allowed_groups_user_id",
				Columns:    []*schema.Column{UserAllowedGroupsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_allowed_groups_group_id",
				Columns:    []*schema.Column{UserAllowedGroupsColumns[1]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		AccountsTable,
		BalanceLogsTable,
		GroupsTable,
		OrdersTable,
		PluginsTable,
		PluginSourcesTable,
		ProxiesTable,
		SettingsTable,
		UsageLogsTable,
		UsersTable,
		UserSubscriptionsTable,
		AccountGroupsTable,
		UserAllowedGroupsTable,
	}
)

func init() {
	APIKeysTable.ForeignKeys[0].RefTable = GroupsTable
	APIKeysTable.ForeignKeys[1].RefTable = UsersTable
	AccountsTable.ForeignKeys[0].RefTable = ProxiesTable
	BalanceLogsTable.ForeignKeys[0].RefTable = UsersTable
	OrdersTable.ForeignKeys[0].RefTable = UsersTable
	UsageLogsTable.ForeignKeys[0].RefTable = APIKeysTable
	UsageLogsTable.ForeignKeys[1].RefTable = AccountsTable
	UsageLogsTable.ForeignKeys[2].RefTable = GroupsTable
	UsageLogsTable.ForeignKeys[3].RefTable = UsersTable
	UserSubscriptionsTable.ForeignKeys[0].RefTable = GroupsTable
	UserSubscriptionsTable.ForeignKeys[1].RefTable = UsersTable
	AccountGroupsTable.ForeignKeys[0].RefTable = AccountsTable
	AccountGroupsTable.ForeignKeys[1].RefTable = GroupsTable
	UserAllowedGroupsTable.ForeignKeys[0].RefTable = UsersTable
	UserAllowedGroupsTable.ForeignKeys[1].RefTable = GroupsTable
}
