// Code generated by ent, DO NOT EDIT.

package group

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldPlatform, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldRateMultiplier, v))
}

// IsExclusive applies equality check predicate on the "is_exclusive" field. It's identical to IsExclusiveEQ.
func IsExclusive(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldIsExclusive, v))
}

// ServiceTier applies equality check predicate on the "service_tier" field. It's identical to ServiceTierEQ.
func ServiceTier(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldServiceTier, v))
}

// ForceInstructions applies equality check predicate on the "force_instructions" field. It's identical to ForceInstructionsEQ.
func ForceInstructions(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldForceInstructions, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldNote, v))
}

// SortWeight applies equality check predicate on the "sort_weight" field. It's identical to SortWeightEQ.
func SortWeight(v int) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldSortWeight, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldPlatform, v))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldRateMultiplier, v))
}

// IsExclusiveEQ applies the EQ predicate on the "is_exclusive" field.
func IsExclusiveEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldIsExclusive, v))
}

// IsExclusiveNEQ applies the NEQ predicate on the "is_exclusive" field.
func IsExclusiveNEQ(v bool) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldIsExclusive, v))
}

// SubscriptionTypeEQ applies the EQ predicate on the "subscription_type" field.
func SubscriptionTypeEQ(v SubscriptionType) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldSubscriptionType, v))
}

// SubscriptionTypeNEQ applies the NEQ predicate on the "subscription_type" field.
func SubscriptionTypeNEQ(v SubscriptionType) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldSubscriptionType, v))
}

// SubscriptionTypeIn applies the In predicate on the "subscription_type" field.
func SubscriptionTypeIn(vs ...SubscriptionType) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldSubscriptionType, vs...))
}

// SubscriptionTypeNotIn applies the NotIn predicate on the "subscription_type" field.
func SubscriptionTypeNotIn(vs ...SubscriptionType) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldSubscriptionType, vs...))
}

// QuotasIsNil applies the IsNil predicate on the "quotas" field.
func QuotasIsNil() predicate.Group {
	return predicate.Group(sql.FieldIsNull(FieldQuotas))
}

// QuotasNotNil applies the NotNil predicate on the "quotas" field.
func QuotasNotNil() predicate.Group {
	return predicate.Group(sql.FieldNotNull(FieldQuotas))
}

// ModelRoutingIsNil applies the IsNil predicate on the "model_routing" field.
func ModelRoutingIsNil() predicate.Group {
	return predicate.Group(sql.FieldIsNull(FieldModelRouting))
}

// ModelRoutingNotNil applies the NotNil predicate on the "model_routing" field.
func ModelRoutingNotNil() predicate.Group {
	return predicate.Group(sql.FieldNotNull(FieldModelRouting))
}

// ServiceTierEQ applies the EQ predicate on the "service_tier" field.
func ServiceTierEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldServiceTier, v))
}

// ServiceTierNEQ applies the NEQ predicate on the "service_tier" field.
func ServiceTierNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldServiceTier, v))
}

// ServiceTierIn applies the In predicate on the "service_tier" field.
func ServiceTierIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldServiceTier, vs...))
}

// ServiceTierNotIn applies the NotIn predicate on the "service_tier" field.
func ServiceTierNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldServiceTier, vs...))
}

// ServiceTierGT applies the GT predicate on the "service_tier" field.
func ServiceTierGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldServiceTier, v))
}

// ServiceTierGTE applies the GTE predicate on the "service_tier" field.
func ServiceTierGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldServiceTier, v))
}

// ServiceTierLT applies the LT predicate on the "service_tier" field.
func ServiceTierLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldServiceTier, v))
}

// ServiceTierLTE applies the LTE predicate on the "service_tier" field.
func ServiceTierLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldServiceTier, v))
}

// ServiceTierContains applies the Contains predicate on the "service_tier" field.
func ServiceTierContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldServiceTier, v))
}

// ServiceTierHasPrefix applies the HasPrefix predicate on the "service_tier" field.
func ServiceTierHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldServiceTier, v))
}

// ServiceTierHasSuffix applies the HasSuffix predicate on the "service_tier" field.
func ServiceTierHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldServiceTier, v))
}

// ServiceTierEqualFold applies the EqualFold predicate on the "service_tier" field.
func ServiceTierEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldServiceTier, v))
}

// ServiceTierContainsFold applies the ContainsFold predicate on the "service_tier" field.
func ServiceTierContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldServiceTier, v))
}

// ForceInstructionsEQ applies the EQ predicate on the "force_instructions" field.
func ForceInstructionsEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldForceInstructions, v))
}

// ForceInstructionsNEQ applies the NEQ predicate on the "force_instructions" field.
func ForceInstructionsNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldForceInstructions, v))
}

// ForceInstructionsIn applies the In predicate on the "force_instructions" field.
func ForceInstructionsIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldForceInstructions, vs...))
}

// ForceInstructionsNotIn applies the NotIn predicate on the "force_instructions" field.
func ForceInstructionsNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldForceInstructions, vs...))
}

// ForceInstructionsGT applies the GT predicate on the "force_instructions" field.
func ForceInstructionsGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldForceInstructions, v))
}

// ForceInstructionsGTE applies the GTE predicate on the "force_instructions" field.
func ForceInstructionsGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldForceInstructions, v))
}

// ForceInstructionsLT applies the LT predicate on the "force_instructions" field.
func ForceInstructionsLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldForceInstructions, v))
}

// ForceInstructionsLTE applies the LTE predicate on the "force_instructions" field.
func ForceInstructionsLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldForceInstructions, v))
}

// ForceInstructionsContains applies the Contains predicate on the "force_instructions" field.
func ForceInstructionsContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldForceInstructions, v))
}

// ForceInstructionsHasPrefix applies the HasPrefix predicate on the "force_instructions" field.
func ForceInstructionsHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldForceInstructions, v))
}

// ForceInstructionsHasSuffix applies the HasSuffix predicate on the "force_instructions" field.
func ForceInstructionsHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldForceInstructions, v))
}

// ForceInstructionsEqualFold applies the EqualFold predicate on the "force_instructions" field.
func ForceInstructionsEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldForceInstructions, v))
}

// ForceInstructionsContainsFold applies the ContainsFold predicate on the "force_instructions" field.
func ForceInstructionsContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldForceInstructions, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldNote, v))
}

// SortWeightEQ applies the EQ predicate on the "sort_weight" field.
func SortWeightEQ(v int) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldSortWeight, v))
}

// SortWeightNEQ applies the NEQ predicate on the "sort_weight" field.
func SortWeightNEQ(v int) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldSortWeight, v))
}

// SortWeightIn applies the In predicate on the "sort_weight" field.
func SortWeightIn(vs ...int) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldSortWeight, vs...))
}

// SortWeightNotIn applies the NotIn predicate on the "sort_weight" field.
func SortWeightNotIn(vs ...int) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldSortWeight, vs...))
}

// SortWeightGT applies the GT predicate on the "sort_weight" field.
func SortWeightGT(v int) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldSortWeight, v))
}

// SortWeightGTE applies the GTE predicate on the "sort_weight" field.
func SortWeightGTE(v int) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldSortWeight, v))
}

// SortWeightLT applies the LT predicate on the "sort_weight" field.
func SortWeightLT(v int) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldSortWeight, v))
}

// SortWeightLTE applies the LTE predicate on the "sort_weight" field.
func SortWeightLTE(v int) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldSortWeight, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, AccountsTable, AccountsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAllowedUsers applies the HasEdge predicate on the "allowed_users" edge.
func HasAllowedUsers() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, AllowedUsersTable, AllowedUsersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAllowedUsersWith applies the HasEdge predicate on the "allowed_users" edge with a given conditions (other predicates).
func HasAllowedUsersWith(preds ...predicate.User) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newAllowedUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKeys applies the HasEdge predicate on the "api_keys" edge.
func HasAPIKeys() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, APIKeysTable, APIKeysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeysWith applies the HasEdge predicate on the "api_keys" edge with a given conditions (other predicates).
func HasAPIKeysWith(preds ...predicate.APIKey) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newAPIKeysStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubscriptions applies the HasEdge predicate on the "subscriptions" edge.
func HasSubscriptions() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SubscriptionsTable, SubscriptionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionsWith applies the HasEdge predicate on the "subscriptions" edge with a given conditions (other predicates).
func HasSubscriptionsWith(preds ...predicate.UserSubscription) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newSubscriptionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLogs applies the HasEdge predicate on the "usage_logs" edge.
func HasUsageLogs() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogsWith applies the HasEdge predicate on the "usage_logs" edge with a given conditions (other predicates).
func HasUsageLogsWith(preds ...predicate.UsageLog) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newUsageLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Group) predicate.Group {
	return predicate.Group(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Group) predicate.Group {
	return predicate.Group(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Group) predicate.Group {
	return predicate.Group(sql.NotPredicates(p))
}
